<?php 

/**
	 * Registers and handles DHPress Project functions
	 *
	 * @package DHPress Toolkit
	 * @author DHPress Team
	 * @link http://dhpress.org/download/
	 */

// ================== Global Variables ===================

	// HTML fields added to Custom Fields box in Edit Project admin panel
$prefix = 'project_';
$dhp_project_settings_fields = array (
	array(
		'label'=> 'Project Settings',
		'desc'	=> 'Stores the project_settings string as a JSON object.',
		'id'	=> $prefix.'settings',
		'type'	=> 'textarea'
	),
	array(
		'label'=> 'Icons',
		'desc'	=> 'Icons for categories.',
		'id'	=> $prefix.'icons',
		'type'	=> 'hidden'
	)
);

// ================== Initialize Plug-in ==================

// init action called to initialize a plug-in
add_action( 'init', 'dhp_project_init' );

// dhp_project_init()
// PURPOSE: To create custom post type for Projects in WP

function dhp_project_init()
{
  $labels = array(
    'name' => _x('Projects', 'post type general name'),
    'singular_name' => _x('Project', 'post type singular name'),
    'add_new' => _x('Add New', 'project'),
    'add_new_item' => __('Add New Project'),
    'edit_item' => __('Edit Project'),
    'new_item' => __('New Project'),
    'all_items' => __('Projects'),
    'view_item' => __('View Project'),
    'search_items' => __('Search Projects'),
    'not_found' =>  __('No projects found'),
    'not_found_in_trash' => __('No projects found in Trash'), 
    'parent_item_colon' => '',
    'menu_name' => __('Projects'),
    'menu_icon' => plugins_url( 'dhpress/images/dhpress-plugin-icon.png' )  // Icon Path
  );
  $args = array(
    'labels' => $labels,
    'public' => true,
    'publicly_queryable' => true,
    'show_ui' => true, 
    'show_in_menu' => 'dhp-top-level-handle', 
    'query_var' => true,
    'rewrite' => array('slug' => 'dhp-projects','with_front' => FALSE),
    'capability_type' => 'page',
    'has_archive' => true,
    /* if we want to subclass project types in future (i.e., Entry Points), will need to set 'hierarchical' => true */
    'hierarchical' => false,
    'menu_position' => null,
    /* if hierarchical, then may want to add 'page-attributes' to supports */
    'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments','revisions', 'custom-fields' )
  ); 
  register_post_type('project',$args);
} // dhp_project_init


// add support for theme-specific feature
if ( function_exists( 'add_theme_support' ) ) {
		// enable use of thumbnails
	add_theme_support( 'post-thumbnails' );
		// default Post Thumbnail dimensions
	set_post_thumbnail_size( 32, 37 ); 
}


// ================== Produce Admin Panel Header ==================

// admin_head action called to create header for admin panel
add_action('admin_head', 'plugin_header');

// plugin_header()
// PURPOSE: Insert DH Press icon into top of administration panel

function plugin_header()
{ ?>
		<style>
		    #icon-dhp-top-level-handle { background:transparent url('<?php echo DHP_PLUGIN_URL .'/images/dhpress-plugin-icon.png';?>') no-repeat; }     
		</style>
<?php
} // plugin_header()


// ================== Preparing the Admin Panel ==================

// admin_init called when user brings up the admin panel -- this sets global variable
add_action('admin_init', 'init_layer_list');

// init_layer_list()
// PURPOSE:	Sets global variable of list of map layers for later use

function init_layer_list()
{
	$layers_global = getLayerList();
} // init_layer_list()


// ================== DHP Maps =====================

// getLayerList()
// PURPOSE: Return list of all dhp-maps in DHP site
// RETURNS: array [layerID, layerName, layerCat, layerType, layerTypeId]
// TO DO:	Wrap into Project object class or move to Map object?

function getLayerList()
{
	$layers = array();
	$args = array( 'post_type' => 'dhp-maps', 'posts_per_page' => -1 );
	$loop = new WP_Query( $args );
	$layerCount=0;
	while ( $loop->have_posts() ) : $loop->the_post();
	//var $tempLayers = array();
		$layer_id = get_the_ID();
		$layer_name = get_the_title();
		$layer_use = get_post_meta($layer_id, 'dhp_map_category',true);
		$layer_type = get_post_meta($layer_id, 'dhp_map_type',true);
		$layer_typeid = get_post_meta($layer_id, 'dhp_map_typeid',true);
		$layerCount++;
		
		array_push($layers,array( 'layerID'=>$layer_id,
		 'layerName'=>$layer_name,
		 'layerCat'=>$layer_use,
		 'layerType'=>$layer_type,
		 'layerTypeId'=>$layer_typeid
		 ));
				
	endwhile;
	wp_reset_query();

	return $layers;
} // getLayerList()

// dhp_build_HTML_maplayer_options($layerArray)
// PURPOSE: Create HTML for option list based on map layers
// INPUT:	$layerArray = array of maps generated by getLayerList()
// ASSUMES:	WP slug for map is map name in which spaces replaced by '-'
// RETURNS:	string of HTML <option id='layerID' class='layerCatSlug' data-mapType='type-layerType' value='layerTypeId'> name </option>
// TO DO:	Move to Map class?

function dhp_build_HTML_maplayer_options($layerArray)
{
	$optionHtml ='';
	foreach ($layerArray as $layer) {
			// 
		$tempCat = str_replace(' ','-',$layer['layerCat']);
		$tempType = 'type-'.$layer['layerType'];
		//$optionHtml .= '{ "id" : "'.$layer['layerID'].'", "name" : "'.$layer['layerName'].'", "usetype" : "'.$layer['layerCat'].'"},';
		$optionHtml .= '<option id="'.$layer['layerID'].
		'" class="'.$tempCat.'" data-mapType="'.$tempType.
		'" value="'.$layer['layerTypeId'].'" >'.$layer['layerName'].'</option>';
	}
	return $optionHtml;
} // dhp_build_HTML_maplayer_options()


//============================ Customize for Project Posts ============================

// post_updated_messages enables us to customize the messages for our custom post types
add_filter( 'post_updated_messages', 'dhp_project_updated_messages' );

// dhp_project_updated_messages()
// PURPOSE:	Supply strings specific to Project custom type
// ASSUMES:	Global variables $post, $post_ID set

function dhp_project_updated_messages( $messages )
{
  global $post, $post_ID;

  $messages['project'] = array(
    0 => '', // Unused. Messages start at index 1.
    1 => sprintf( __('Project updated. <a href="%s">View project</a>'), esc_url( get_permalink($post_ID) ) ),
    2 => __('Custom field updated.'),
    3 => __('Custom field deleted.'),
    4 => __('Project updated.'),
    /* translators: %s: date and time of the revision */
    5 => isset($_GET['revision']) ? sprintf( __('Project restored to revision from %s'), wp_post_revision_title( (int) $_GET['revision'], false ) ) : false,
    6 => sprintf( __('Project published. <a href="%s">View project</a>'), esc_url( get_permalink($post_ID) ) ),
    7 => __('Project saved.'),
    8 => sprintf( __('Project submitted. <a target="_blank" href="%s">Preview project</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),
    9 => sprintf( __('Project scheduled for: <strong>%1$s</strong>. <a target="_blank" href="%2$s">Preview project</a>'),
      // translators: Publish box date format, see http://php.net/date
      date_i18n( __( 'M j, Y @ G:i' ), strtotime( $post->post_date ) ), esc_url( get_permalink($post_ID) ) ),
    10 => sprintf( __('Project draft updated. <a target="_blank" href="%s">Preview project</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),
  );

  return $messages;
} // dhp_project_updated_messages()


// =========================== Customize handling of taxonomies ============================

// add custom taxonomies for each project when plugin is initialized
add_action( 'init', 'create_tax_for_projects', 0 );

// create_tax_for_projects()
// PURPOSE: Create custom types for all existing projects if they don't exist
//			Taxonomy "head" name for each project is 'dhp_tax_<project_id>'

function create_tax_for_projects()
{
	$args = array( 'post_type' => 'project', 'posts_per_page' => -1 );
	$projects = get_posts($args);
	if ($projects) {
		foreach ( $projects as $project ) {
			$projectTax = 'dhp_tax_'.$project->ID;
			$projectName = $project->post_title;
			$projectSlug = $project->post_name;
			$taxonomy_exist = taxonomy_exists($projectTax);
			//returns true
			if(!$taxonomy_exist) {
				dhp_create_tax($projectTax,$projectName,$projectSlug);
			}
		}
	}
} // create_tax_for_projects()


// dhp_create_tax($taxID,$taxName,$taxSlug)
// PURPOSE: Create custom taxonomy for a specific Project in WP
// INPUT:	$taxID = taxonomy name (dhp_tax_<project_id>), $taxName = project title, $taxSlug = project slug

function dhp_create_tax($taxID,$taxName,$taxSlug)
{
	// Add new taxonomy, make it hierarchical (like categories)
  $labels = array(
    'name' => _x( $taxName, 'taxonomy general name' ),
    'singular_name' => _x( $taxName, 'taxonomy singular name' ),
    'search_items' =>  __( 'Search Terms' ),
    'all_items' => __( 'All Terms' ),
    'parent_item' => __( 'Parent Term' ),
    'parent_item_colon' => __( 'Parent Term:' ),
    'edit_item' => __( 'Edit Term' ), 
    'update_item' => __( 'Update Term' ),
    'add_new_item' => __( 'Add New Term' ),
    'new_item_name' => __( 'New Term Name' ),
    'menu_name' => __( 'Term' ),
  ); 	

  register_taxonomy($taxID,array('dhp-markers'), array(
    'hierarchical' => true,
    'public' => true,
    'labels' => $labels,
    'show_ui' => true,
    'show_in_nav_menus' => false,
    'query_var' => true,
    'rewrite' => array('hierarchical' => true, 'slug' => 'dhp-projects/'.$taxSlug, 'with_front' => false)
  ));
} // dhp_create_tax()

// admin_head called when compiling header of admin panel
add_action( 'admin_head' , 'show_tax_on_project_markers' );

// show_tax_on_project_markers()
// PURPOSE: Called when compiling project admin panel to remove the editing boxes for
//			all taxonomies other than those connected to this project
// ASSUMES:	$post is set to a project (i.e., that we are editing or viewing project)

function show_tax_on_project_markers()
{
	global $post;

	$projectID = get_post_meta($post->ID,'project_id');
	$project = get_post($projectID[0]);
	$projectTaxSlug = 'dhp_tax_'.$project->ID;
	$dhpTaxs = get_taxonomies();

	foreach ($dhpTaxs as $key => $value) {
		if($value!=$projectTaxSlug) {
			remove_meta_box( $value.'div', 'dhp-markers', 'side' );
		}
	}
} // show_tax_on_project_markers()


// add_meta_boxes called when Edit Post runs
add_action('add_meta_boxes', 'add_dhp_project_icons_box');

// add_dhp_project_icons_box()
// PURPOSE:	Add the editing box for Marker icons (shown on maps)

function add_dhp_project_icons_box()
{
    add_meta_box(
		'dhp_icons_box', // $id
		'Marker Icons', // $title
		'show_dhp_project_icons_box', // $callback
		'project', // $page
		'side', // $context 
		'default'); // $priority
} // add_dhp_project_icons_box()

function show_dhp_project_icons_box()
{
	//dhp_deploy_icons();
	bdw_get_images();
} // show_dhp_project_icons_box()


// bdw_get_images()
// PURPOSE: Create HTML icon box on right sidebox
// SIDE FX:	Outputs HTML of thumbnail images of images associated with post
// ASSUMES:	$post global is set to Project post
// TO DO:	Wrap in Project class

function bdw_get_images()
{
	global $post;

    // Get the post ID
    $iPostID = $post->ID;
 
    // Get images associated with this Project post
    $arrImages = get_children('post_type=attachment&post_mime_type=image&numberpost=-1&post_parent=' . $iPostID );
 
    // If images exist for this page
    if($arrImages) {
 
        // Get array keys representing attached image numbers
        $arrKeys = array_keys($arrImages);

 
        $sImgString .= '<div class="misc-pub-section icons">';
 
        // UNCOMMENT THIS IF YOU WANT THE FULL SIZE IMAGE INSTEAD OF THE THUMBNAIL
        //$sImageUrl = wp_get_attachment_url($iNum);
        $i = 0;
 		foreach ($arrKeys as $field) {
 			// Get the first image attachment
        	$iNum = $arrKeys[$i];
 			$i++;
        	// Get the thumbnail url for the attachment
       		$sThumbUrl = wp_get_attachment_thumb_url($iNum);
        	// Build the <img> string
        	$sImgString .= '<a id="'.$iNum.'" >' .
                            '<img src="' . $sThumbUrl . '"/>' .
                        '</a>';
 		}
 		$sImgString .= '</div>';
        // Print the image
        echo $sImgString;
    }
} // bdw_get_images()


// add_meta_boxes called when Edit Post runs
add_action('add_meta_boxes', 'add_dhp_project_settings_box');

// add_dhp_project_settings_box()
// PURPOSE: Called when Project is edited in admin panel to create Project-specific GUI

function add_dhp_project_settings_box()
{
    add_meta_box(
		'dhp_settings_box', 			// id of edit box
		'Project Details',				// textual title of box
		'show_dhp_project_settings_box', // name of callback function
		'project',						// custom page name
		'normal',						// part of page to add box
		'high'); 						// priority
} // add_dhp_project_settings_box()

// show_dhp_project_settings_box()
// PURPOSE:		Called by WP to create HTML for hidden fields (in admin panel) which save Project state
//					for auto-save
// ASSUMPTIONS:	Global $post is set to point to post for current project
//				Global $dhp_project_settings_fields is set to array of strings describing HTML controls
// SIDE-FX:		Sets _PROJECT_ID_ global to ID of project post
// TO DO:		Don't use _PROJECT_ID_ global! tried removing logic but didn't work!
//				Put all HTML producing logic into special generalized function

function show_dhp_project_settings_box()
{
	global $dhp_project_settings_fields, $post;
	define("_PROJECT_ID_", $post->ID);

	// Load post id for project settings
	echo '<input type="hidden" id="dhp-projectid" value="'.$post->ID.'"/>';
	// Use nonce for verification
	echo '<input type="hidden" name="dhp_project_settings_box_nonce" value="'.wp_create_nonce(basename(__FILE__)).'" />';
	//echo '<div id="map-divs"></div><button id="locate">Locate me!</button>';

	// Begin the field table and loop
	echo '<table class="project-form-table">';
	foreach ($dhp_project_settings_fields as $field) {
		// get value of this field if it exists for this post
		$meta = get_post_meta($post->ID, $field['id'], true);
		// begin a table row with

				switch($field['type']) {
					// case items will go here
					// text
					case 'text':
						echo '<tr>
							<th><label for="'.$field['id'].'">'.$field['label'].'</label></th>
							<td>';
						echo '<input type="text" name="'.$field['id'].'" id="'.$field['id'].'" value="'.$meta.'" size="30" />
							<br /><span class="description">'.$field['desc'].'</span>';
							echo '</td></tr>';
						break;
					// textarea
					case 'textarea':
						echo '<tr>
							<th><label for="'.$field['id'].'">'.$field['label'].'</label></th>
							<td>';
						echo '<textarea name="'.$field['id'].'" id="'.$field['id'].'" cols="60" rows="4">'.$meta.'</textarea>
							<br /><span class="description">'.$field['desc'].'</span>';
							echo '</td></tr>';
						break;
					// checkbox
					case 'checkbox':
						echo '<tr>
							<th><label for="'.$field['id'].'">'.$field['label'].'</label></th>
							<td>';
						echo '<input type="checkbox" name="'.$field['id'].'" id="'.$field['id'].'" ',$meta ? ' checked="checked"' : '','/>
							<label for="'.$field['id'].'">'.$field['desc'].'</label>';
							echo '</td></tr>';
						break;
					// select
					case 'select':
						echo '<tr>
							<th><label for="'.$field['id'].'">'.$field['label'].'</label></th>
							<td>';
						echo '<select name="'.$field['id'].'" id="'.$field['id'].'">';
						foreach ($field['options'] as $option) {
							echo '<option', $meta == $option['value'] ? ' selected="selected"' : '', ' value="'.$option['value'].'">'.$option['label'].'</option>';
						}
						echo '</select><br /><span class="description">'.$field['desc'].'</span>';
						echo '</td></tr>';
						break;
					// textarea
					case 'hidden':
						echo '<input type="hidden" name="'.$field['id'].'" id="'.$field['id'].'" value="'.$meta.'" />';
						break;
				} //end switch
		
	} // end foreach
	echo '</table>'; // end table
	
	print_new_bootstrap_html();
} // show_dhp_project_settings_box()

// 'save_post' is called after post is created or updated
add_action('save_post', 'save_dhp_project_settings');

// save_dhp_project_settings($post_id)
// PURPOSE: Save data posted to WP for project based on project_settings_fields
//				(Could also be invoked by Auto-Save feature of WP)
// INPUT:	$post_id is the id of the post updated
// ASSUMES:	$_POST is set to post data
//			$dhp_project_settings_fields describes the data posted
// TO DO:	Simplify saving logic at end

function save_dhp_project_settings($post_id)
{
    global $dhp_project_settings_fields;

    	// is this an update of existing Project post?
	$parent_id = wp_is_post_revision( $post_id );
	
	// verify nonce
	if (!wp_verify_nonce($_POST['dhp_project_settings_box_nonce'], basename(__FILE__)))
		return $post_id;

	// check autosave
	if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE)
		return $post_id;

	// check permissions
	if ('page' == $_POST['post_type']) {
		if (!current_user_can('edit_page', $post_id))
			return $post_id;
		} elseif (!current_user_can('edit_post', $post_id)) {
			return $post_id;
	}

	if ( $parent_id ) {
		// loop through fields and save the data
		$parent  = get_post( $parent_id );
		
		foreach ($dhp_project_settings_fields as $field) {
			$old = get_post_meta( $parent->ID, $field['id'], true);
			$new = $_POST[$field['id']];
			if ($new && $new != $old) {
				update_metadata( 'post', $post_id, $field['id'], $new);
			} elseif ('' == $new && $old) {
				delete_metadata( 'post', $post_id, $field['id'], $old);
			}
		} // end foreach
	} else {
		// loop through fields and save the data
		foreach ($dhp_project_settings_fields as $field) {
			$old = get_post_meta($post_id, $field['id'], true);
			$new = $_POST[$field['id']];
			if ($new && $new != $old) {
				update_post_meta($post_id, $field['id'], $new);
			} elseif ('' == $new && $old) {
				delete_post_meta($post_id, $field['id'], $old);
			}
		} // end foreach
	}
} // save_dhp_project_settings()

// createMetaValueArray($custom_name,$project_id)
// PURPOSE: Calculate the unique values for a field in all markers of a project
// INPUT:	$custom_name = the field name within a marker; $project_id = ID of the Project (post)
// RETURNS:	Array of unique values
// TO DO:	A faster way to do this? Create a sorted array/list?

function createMetaValueArray($custom_name,$project_id)
{
		//loop through all markers in project & add to array
	$moteArray = array();
	$projectObj = get_post($project_id);
	$dhp_tax_name = 'dhp_tax_'.$projectObj->ID;

	$args = array('post_type' => 'dhp-markers', 'meta_key' => 'project_id', 'meta_value'=>$project_id, 'posts_per_page' => -1 );
	$tempMetaArray = array();
	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();
		$tempMetaValue = get_post_meta(get_the_ID(), $custom_name, true);

		array_push($tempMetaArray, $tempMetaValue);
	endwhile;

	$result = array_unique($tempMetaArray);
	return $result;
} // createMetaValueArray()

// createUniqueCustomFieldArray($the_id)
// PURPOSE:	To determine all of the custom fields associated with the Project
// RETURNS: Array of all unique custom fields of all marker posts associated with the Project
// TO DO:	A faster way to do this? Create a sorted array/list?

function createUniqueCustomFieldArray($project_id)
{
		//loop through all markers in project adding to array
	$custom_field_array = array();

	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$project_id, 'posts_per_page' => -1 );
	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();

		$marker_id = get_the_ID();
		$temp_custom_field_keys = get_post_custom_keys($marker_id);

		foreach($temp_custom_field_keys as $key => $value) {
			$valuet = trim($value);
				// exclude WP internal fields
     		if ( '_' == $valuet{0} )
      			continue;
			array_push($custom_field_array, $value);
		}

	endwhile;
	$unique_custom_fields = array_unique($custom_field_array);

	return $unique_custom_fields;
} // createUniqueCustomFieldArray()


// invertLatLon($latlon)
// RETURNS:	New comma separated string with elements reversed
// INPUT:	String with 2 comma-separated numbers
// TO DO:	Better error checking? Move to Map class?

function invertLatLon($latlon)
{
	if($lonlat==','){
		return '';
	}

	if($latlon&&$latlon!=',') {
		$tempLonLat = split(',',$latlon);
		return array($tempLonLat[1],$tempLonLat[0]);
	}

} // invertLatLon()

// getIconsForTerms($parent_term, $taxonomy)
// PURPOSE: Get all of the visual features associated via metadata with the taxonomic terms associated with 1 Mote
// INPUT:	$parent_term = Object for mote/top-level term
//			$taxonomy = name of taxonomy for Project (dhp_tax_<pID>)
// RETURNS: Description of Legends to appear on Map in the following format:
			// {	"type" : "filter",
			// 		"name" : String (top-level-mote-name),
			// 		"terms" :				// 1st level terms & their children
			// 		[
			// 		  {	"name" :  String (inc. top-level-mote-name),
			// 			"id" : integer,
			// 			"icon_url": URL,
			// 			"children_names" : [ Strings of names ],
			// 			"children" :
			// 			[
			// 			  {	"name" : String,
			// 				"term_id" : integer,
			// 				"parent" : integer,
			// 				"count" : String,
			// 				"slug" : String,
			// 				"description" : String,
			// 				"term_taxonomy_id" : String,
			// 				"taxonomy" : String,
			// 				"term_group" : String
			//			  }, ...
			// 			]
			// 		  }, ...
			// 		],
			// 	}

function getIconsForTerms($parent_term, $taxonomy)
{
	$children_names  = array();
	$filter_children = array();
	$icon_url        = get_term_meta($parent_term->term_id,'icon_url',true);

	$filter_object['type']  = "filter";
	$filter_object['name']  = $parent_term->name;
	$filter_object['terms'] = array();

		// Begin with top-level mote name
	$filter_parent['name']     = $parent_term->name;
	$filter_parent['id']       = intval($parent_term->term_id);
	$filter_parent['icon_url'] = $icon_url;
	array_push($filter_object['terms'], $filter_parent);

	$myargs = array( 'orderby'       => 'term_group',
		 			 'hide_empty'    => false, 
					 'parent'        => $parent_term->term_id );
	$children_terms  = get_terms( $taxonomy, $myargs );

		// Go through each of the values in the category
	foreach ($children_terms as $child) {
		array_push($children_names, $child->name);
			// Get any children of this category
		$childArgs = array( 'orderby' 		=> 'term_group',
		 					'hide_empty'    => false,
							'parent'        => $child->term_id );
		$children_terms2 = get_terms( $taxonomy, $childArgs );
		$children_names2 = array();
		foreach ($children_terms2 as $child2) {
				// convert IDs from String to Integer
			$child2->term_id = intval($child2->term_id);
			$child2->parent = intval($child2->parent);
			array_push($children_names2, $child2->name);
		}
		$icon_url = get_term_meta($child->term_id,'icon_url',true);

		$temp_child_filter['name']        = $child->name;
		$temp_child_filter['id']          = intval($child->term_id);
		$temp_child_filter['icon_url']    = $icon_url;
		$temp_child_filter['children_names'] = $children_names2;
		$temp_child_filter['children']    = $children_terms2;

		array_push($filter_object['terms'], $temp_child_filter);
	}
		// Update top-level mote pushed near top of function
	$filter_parent['children_names'] = $children_names;
	$filter_parent['children'] = $children_terms;

	return $filter_object;
} // getIconsForTerms()

// getMoteFromName($settings,$moteName)
// RETURNS: JSON object in $settings whose name is $moteName
// TO DO:   Wrap into Project class
function getMoteFromName($settings,$moteName)
{ 
	foreach( $settings['motes'] as $mote)
		if($mote['name']==$moteName)
			return $mote;
} // getMoteFromName()

// dhp_get_term_by_parent($link_terms, $terms, $tax)
// PURPOSE:	Get link to category page based on category value, if one of $terms appears in $link_terms
// INPUT:	$link_terms = array of taxonomic terms
//			$terms = array of terms associated with a particular Marker
//			$tax = "dhp_tax_"<pID>
// RETURNS: PermaLink for marker's term (from $terms) that appears in $link_terms
// ASSUMES:	That strings in $terms have been HTML-escaped

function dhp_get_term_by_parent($link_terms, $terms, $tax)
{
	foreach( $terms as $term ) {
		$real_term = get_term_by('id', $term, $tax);
		$intersect = array_intersect(array($real_term->term_id), $link_terms);
		if ($intersect) {
			 $term_link = get_term_link($real_term);
			 return $term_link;
		}
	}
} // dhp_get_term_by_parent()


// ========================================= AJAX calls ======================================

add_action( 'wp_ajax_dhp_get_group_feed', 'dhp_get_group_feed' );
add_action( 'wp_ajax_nopriv_dhp_get_group_feed', 'dhp_get_group_feed' );

// dhp_get_group_feed($tax_name,$term_name)
// PURPOSE: Ajax hook that will return all Markers in this Project associated with a specific term
//				and their associated data (as configured in project settings)
// INPUT:	$tax_name = "dhp_tax_"<pID>
// 			$term_name = taxonomic term created for Mote value
// RETURNS:	Feature collection containing Markers associated with term
// NOTE:    Which specific features will be returned in results will depend upon visualization; that is,
//				category/legend MUST be augmented by visual features

function dhp_get_group_feed($tax_name,$term_name)
{
	$pieces = explode("dhp_tax_", $tax_name);
    $projectID = get_page($pieces[1],OBJECT,'project');
    $project_settings = json_decode(get_post_meta($projectID->ID,'project_settings',true),true);
    $the_term = get_term_by('name', $term_name, $tax_name);

    	// Initialize settings in case not used
	$map_pointsMote = $cordMote = $audio = $transcript = $timecode = null;

    	// Accumulate settings that are specified
	foreach( $project_settings['entry-points'] as $eps) {
		switch ($eps['type']) {
		case "map":
			// $filter_parentMote = getMoteFromName( $project_settings, $eps['settings']['filter-data'] );
			// $mapFilter = $eps['settings']['filter-data'];
				// Get mote responsible for setting Lat/Lon on map
			$map_pointsMote = getMoteFromName( $project_settings, $eps['settings']['marker-layer'] );
				// Ensure type is Lat/Lon
			if($map_pointsMote['type']=='Lat/Lon Coordinates'){
					// use "," as default delimiter
				if(!$map_pointsMote['delim']) { $map_pointsMote['delim']=','; }
					// Is custom-fields a concatenation of two other fields?
				$cordMote = split($map_pointsMote['delim'],$map_pointsMote['custom-fields']);
				//array of custom fields
				//$cordMote = $map_pointsMote['custom-fields'];
			}
			break;
		case "transcript":
			$audio = getMoteFromName( $project_settings, $eps['settings']['audio'] );
			$transcript = getMoteFromName( $project_settings, $eps['settings']['transcript'] );
			$timecode = getMoteFromName( $project_settings, $eps['settings']['timecode'] );
			break;
		}
	}

	$feature_collection['type'] = "FeatureCollection";
	$feature_collection['features'] = array();

	$args = array(
	    'post_type'=> 'dhp-markers',
	    'posts_per_page' => '-1',
	    'tax_query' => array(
			array(
				'taxonomy' => $tax_name,
				'field' => 'slug',
				'terms' => $the_term->slug
			)
		)
    );
	$loop = new WP_Query( $args );

		// Go through all marker posts that match
	while ( $loop->have_posts() ) : $loop->the_post();
			// Get its value(s) for this legend/category
		$marker_id = get_the_ID();
		$args1 = array("fields" => "names");
		$post_terms = wp_get_post_terms( $marker_id, $tax_name, $args1 );

		$this_feature = array();
		$this_feature['properties']= array();
		$this_feature['properties']['title'] = get_the_title();
		$this_feature['properties']['categories'] = json_encode($post_terms);

			// Get all potential visualization features

			// Get audio transcripts features
		if (!is_null($audio)) {
			$audio_val = get_post_meta($marker_id,$audio['custom-fields']);
			$timecode_val = get_post_meta($marker_id,$timecode['custom-fields'],true);
			$this_feature['properties']['audio'] = $audio_val[0];
			$this_feature['properties']['timecode'] = $timecode_val;
		}

			// Get map visualization features
		if (!is_null($map_pointsMote)) {
				// retrieve coordinate data
			if(count($cordMote)==2) {
				$temp_lat = get_post_meta($marker_id,$cordMote[0]);
				$temp_lon = get_post_meta($marker_id,$cordMote[1]);
				$temp_latlon = $temp_lat[0].','.$temp_lon[0];

				$lonlat = invertLatLon($temp_latlon);
			} else if(count($cordMote)==1) {
				$temp_latlon = get_post_meta($marker_id,$cordMote[0]);
				$lonlat = invertLatLon($temp_latlon[0]);
			}

			$this_feature['type'] = 'Feature';
			$this_feature['geometry'] = array();

			$this_feature['geometry']['type'] = 'Point';
			$this_feature['geometry']['coordinates'] = $lonlat;
			//properties
			//array_push($markerArray,$json_string); 
		}
		array_push($feature_collection['features'],$this_feature);

	endwhile;
	
	return $feature_collection;
} // dhp_get_group_feed()


// createMarkerArray($project_id)
// PURPOSE:	Creates Legends and Feature Collections Object (as per OpenLayer) when looking at a project page;
//			That is, return array describing all markers based on filter and visualization
// INPUT:	$project_id = ID of Project to view
// RETURNS: JSON object describing all markers associated with Project
//			[0..n] is as getIconsForTerms above; [n+1] is as follows:
			// {	"type": "FeatureCollection",
			// 	 	"features" :
			// 		[
			// 			{ "type" : "Feature",
			// 			  "geometry" : {"type" : "Point", "coordinates" : longlat}, 
			// 			  "properties" :
			// 				[
			// 					"title" : String,
			// 					"categories" : [ integer IDs of category terms ],
			// 					"content" : [ { moteName : moteValue }, ... ],
			// 					"audio" : String,
			// 					"transcript" : String,
			// 					"transcript2" : String,
			// 					"timecode" : String,
			// 					"link" : URL,
			// 					"link2" : URL
			// 				],
			// 			}, ...
			// 		]
			// 	}
// TO DO:   Do not need to create and pass values in "content" that have corresponding IDs in "categories";
//			We should eliminate this and lookup corresponding feature in filter data acc. to ID

function createMarkerArray($project_id)
{
		// initialize result array
	$json_Object = array();
		// get Project info
	$project_object = get_post($project_id);
	$project_tax = 'dhp_tax_'.$project_object->ID;
	$project_settingsA = get_post_meta($project_id,'project_settings', true);
	$project_settings = json_decode($project_settingsA,true);

    	// Initialize settings in case not used
	$map_pointsMote = $cordMote = $filters = $audio = $transcript = $timecode = null;

    	// Accumulate settings that are specified
	foreach( $project_settings['entry-points'] as $eps) {
		switch ($eps['type']) {
		case "map":
				// Which field used to encode Lat-Long on map?
			$map_pointsMote = getMoteFromName( $project_settings, $eps['settings']['marker-layer'] );
			if($map_pointsMote['type']=='Lat/Lon Coordinates'){
				if(!$map_pointsMote['delim']) { $map_pointsMote['delim']=','; }
				$cordMote = split($map_pointsMote['delim'],$map_pointsMote['custom-fields']);
				//array of custom fields
				//$cordMote = $map_pointsMote['custom-fields'];
			}

				// Find all possible legends for this map -- each marker needs these fields
			$filters = $eps['settings']['filter-data'];
				// Collect all possible category values/tax names for each mote in all filters
			foreach( $filters as $legend ) {
				$parent = get_term_by('name', $legend, $project_tax);
				$parent_term_id = $parent->term_id;
				// $parent_terms = get_terms( $project_tax, array( 'parent' => $parent_term_id, 'orderby' => 'term_group', 'hide_empty' => false ) );
				array_push($json_Object, getIconsForTerms($parent, $project_tax));
			}
			break;
		case "transcript":
			$audio = getMoteFromName( $project_settings, $eps['settings']['audio'] );
			$transcript = getMoteFromName( $project_settings, $eps['settings']['transcript'] );
			$transcript2 = getMoteFromName( $project_settings, $eps['settings']['transcript2'] );			
			$timecode = getMoteFromName( $project_settings, $eps['settings']['timecode'] );
			break;
		}
	}

	//$json_string = '{"type": "FeatureCollection","features": [';
	$json_string['type'] = 'FeatureCollection';
	$feature_array = array();
	//$feature_collection['type'] = "FeatureCollection";
	//$feature_collection['features'] = array();

	$link_parent = $project_settings['views']['link'];
	if($link_parent) {
		if($link_parent=='marker') {
		//$parent_id = get_term_by('name', $link_parent, $project_tax);
			$child_terms = 'marker';
		}
		elseif($link_parent=='no-link') {
			$term_links = 'no-link';
			$child_terms = 'no-link';
		}
		else {
				// translate into category/term ID
			$parent_id = get_term_by('name', $link_parent, $project_tax);
				// find all category terms
			$child_terms = get_term_children($parent_id->term_id, $project_tax);
		}
	}

	$link_parent2 = $project_settings['views']['link2'];
	if($link_parent2) {
		if($link_parent2=='marker') {
		//$parent_id = get_term_by('name', $link_parent, $project_tax);
			$child_terms2 = 'marker';
		}
		elseif($link_parent2=='no-link') {
			$term_links2 = 'no-link';
			$child_terms2 = 'no-link';
		}
		else {
			$parent_id2 = get_term_by('name', $link_parent2, $project_tax);
			$child_terms2 = get_term_children($parent_id2->term_id, $project_tax);
		}
	}

		// Determine whether title is default title of marker post or another field
	$title_mote = $project_settings['views']['title'];
	if ($title_mote != 'the_title') {
		$temp_mote = getMoteFromName( $project_settings, $project_settings['views']['title'] );
		$title_mote = $temp_mote['custom-fields'];
	}

		// Run query to return all marker posts belonging to this Project
	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$project_id, 'posts_per_page' => -1 );
	$loop = new WP_Query( $args );

	while ( $loop->have_posts() ) : $loop->the_post();

		$marker_id = get_the_ID();
		// $tempMarkerValue = get_post_meta($marker_id,$mote_name);
		// $tempMoteArray = split(';',$tempMoteValue[0]);

			// Feature will hold properties and some other values for each marker
		$temp_feature = array();
			// Most data goes into properties field
		$tempProperties = array();

		if($title_mote=='the_title') {
			$title = get_the_title();
		} else {
			$title = get_post_meta($marker_id,$title_mote,true);
		}
		$tempProperties["title"] = $title;
		$temp_feature['type']    = 'Feature';
		
			// Map visualization features?
		if (!is_null($map_pointsMote)) {
			if(count($cordMote)==2) {
				$temp_lat = get_post_meta($marker_id, $cordMote[0], true);
				$temp_lon = get_post_meta($marker_id, $cordMote[1], true);

				$lonlat = array($temp_lon,$temp_lat);
			} elseif(count($cordMote)==1) {
				$temp_latlon = get_post_meta($marker_id, $cordMote[0], true);
				$lonlat = invertLatLon($temp_latlon);
			}
			//$json_string .= $cordMote;
			//$lonlat = invertLatLon($latlon[0]);
			$temp_feature['geometry'] = array("type"=>"Point","coordinates"=> $lonlat);
		}

			// Audio transcript features?
		if (!is_null($audio)) {
			$audio_val = get_post_meta($marker_id,$audio['custom-fields'],true);
			$tempProperties["audio"] = $audio_val;

			$transcript_val = get_post_meta($marker_id, $transcript['custom-fields'],true);
			$tempProperties["transcript"]  = $transcript_val;

			$transcript2_val = get_post_meta($marker_id, $transcript2['custom-fields'],true);
			$tempProperties["transcript2"] = $transcript2_val;

			$timecode_val = get_post_meta($marker_id,$timecode['custom-fields'],true);
			$tempProperties["timecode"]    = $timecode_val;
		}

			// Get all of the legend/category values associated with this marker post
		$args = array('fields' => 'ids');
		$post_terms = wp_get_post_terms( $marker_id, $project_tax, $args );
		$term_array = array();
		foreach( $post_terms as $term) {
				// Convert tax category names into IDs
			array_push($term_array,intval($term));
		}
		$tempProperties["categories"]  = $term_array;

		// $json_string['debug'] = $viewsContent;
		$content_att = array();

			// For each of the legends/categories defined for the View, gather values for this Marker
		$viewsContent = $project_settings['views']['content'];
		if($viewsContent) {
			foreach( $viewsContent as $contentMote ) {
				$content_mote = getMoteFromName( $project_settings, $contentMote );
				$content_type = $content_mote['type'];
				if($content_mote['custom-fields']=='the_content') {
					$content_val = apply_filters('the_content', get_post_field('post_content', $marker_id));
					$content_val = $content_val;
				}
				else {
					$content_val = get_post_meta($marker_id,$content_mote['custom-fields'],true);
				}
				if($content_type=='Image'){
					$content_val = '<img src="'.$content_val.'" />';
				}
				array_push($content_att, array($contentMote => $content_val));
			}
			$tempProperties["content"]     = $content_att;
		}

		if ($link_parent && $child_terms && $child_terms != 'no-link') {
			if ($child_terms=='marker')
				$term_links = get_permalink();
			else
				$term_links = dhp_get_term_by_parent($child_terms, $post_terms, $project_tax);
			if ($term_links)
				$tempProperties["link"] = $term_links;
		}

		if ($link_parent2 && $child_terms2 && $child_terms2 != 'no-link') {
			if ($child_terms2=='marker')
				$term_links2 = get_permalink();
			else
				$term_links2 = dhp_get_term_by_parent($child_terms2, $post_terms, $project_tax);
			if ($term_links2)
				$tempProperties["link2"] = $term_links2;
		}

			// Store all of the properties
		$temp_feature['properties'] = $tempProperties;
			// Save this marker
		if($lonlat) {
			array_push($feature_array,$temp_feature);
		}
		
		
	endwhile;
	//$json_string .= ']';
	$json_string['features'] = $feature_array;
	array_push($json_Object, $json_string);	
	 //$result = array_unique($array)
	return $json_Object;
} // createMarkerArray()


// dateFormatSplit($date_range)
// PURPOSE:	Parse date range into from and to fields in format
//			DATE1-DATE2 = 
// INPUT:	Date as String in format 
// RETURNS: Array where [0] is From-Date and [1] is To-Date
// TO DO:	Not fully implemented

function dateFormatSplit($date_range)
{
		// Approximate date?
	$posA = strpos($date_range, "~");
		// Exact date?
	$posE = strpos($date_range, "-");

	if($posE > 0) {
    	$dateArray = explode('-', $date_range);	
    	if($dateArray[1]=='') {
    		$dateArray[1] = $dateArray[0];
    	}
	}
	if($posA > 0) {
    	$dateArray = explode('~', $date_range);	
    	if($dateArray[1]=='') {
    		$dateArray[1] = $dateArray[0];
   	 	}
	}
	return $dateArray;
} // dateFormatSplit()


// createTimelineArray($project_id)
// PURPOSE: Prepare for timeline view
// INPUT:	$project_id = ID of project
// TO DO:	Not currently used -- Remove hard-coded constants!

function createTimelineArray($project_id)
{
	//loop through all markers in project -add to array
	$timelineArray = array();
	$project_object = get_post($project_id);
	$project_tax = 'dhp_tax_'.$project_object->ID;

	//LOAD PROJECT SETTINGS
	//-get primary category parent

	$parent = get_term_by('name', "Primary Concept", $project_tax);
	//$parent = get_terms($project_tax, array('parent=0&hierarchical=0&number=1'));
	//print_r($parent);
	$parent_term_id = $parent->term_id;
	$parent_terms = get_terms( $project_tax, array( 'parent' => $parent_term_id, 'orderby' => 'term_group' ) );

	$term_icons = getIconsForTerms($parent_terms, $project_tax);

	$json_string = '{"timeline":{"headline":"Long Womens Movement","type":"default","text":"A journey","date":[';
	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$project_id, 'posts_per_page' => -1 );
	$loop = new WP_Query( $args );
	$i = 0;
	while ( $loop->have_posts() ) : $loop->the_post();

		$marker_id = get_the_ID();
		$tempMarkerValue = get_post_meta($marker_id,$mote_name);
		$tempMoteArray = split(';',$tempMoteValue[0]);
		$latlon = get_post_meta($marker_id,'Location0');

		$lonlat = invertLatLon($latlon[0]);
		$title = get_the_title();
		$categories = get_post_meta($marker_id,'Primary Concept');
		$date = get_post_meta($marker_id,'date_range');
		$dateA = dateFormatSplit($date[0]);

		$startDate = $dateA[0];
		$endDate = $dateA[1];
		$args = array("fields" => "names");
		$post_terms = wp_get_post_terms( $marker_id, $project_tax, $args );
		$p_terms;
		foreach ($post_terms as $term ) {
			$p_terms .= $term.',';
		}
		if($i>0) {
			$json_string .= ',';
		}
		else {$i++;}
			
		$json_string .= '{"startDate":"'.$startDate.'","endDate":"'.$endDate.'","headline":"'.$title.'","text":"'.$categories[0].'","asset":{"media":"","credit":"","caption":""}}';

		//array_push($markerArray,$json_string);
	endwhile;

	$json_string .= ']}}';	
	 //$result = array_unique($array)
	return $json_string;
} // createTimelineArray()


// create_custom_field_option_list($cf_array)
// PURPOSE:	Create HTML for option buttons for listing custom fields in print_new_bootstrap_html()
// INPUT:	$cf_array = list of custom fields
// RETURNS:	String containing HTML

function create_custom_field_option_list($cf_array)
{
	$optionHtml .='<option value="">--</option><option value="the_content">Post Content</option>';
	foreach ($cf_array as $key => $value) {
		$optionHtml .='<option value="'.$value.'">'.$value.'</option>';
	}
	return $optionHtml;
} // create_custom_field_option_list()


// print_new_bootstrap_html()
// PURPOSE:	Create the HTML for DHP admin panel for editing a Project
// ASSUMES:	_PROJECT_ID_ global has been set
// TO DO:	Remove use of _PROJECT_ID_  global !

function print_new_bootstrap_html()
{
	// global $dhp_custom_fields, $post;
	global $dhp_custom_fields;

	// $projectPage = get_page($post->ID);
	$projectPage = get_page(_PROJECT_ID_);
	$projectTax_slug = $projectPage->post_name;
//	$dhp_custom_fields = createUniqueCustomFieldArray($post->ID);
	$dhp_custom_fields = createUniqueCustomFieldArray(_PROJECT_ID_);
	echo '<div class="new-bootstrap">
    <div class="row-fluid"> 	
    	<div class="span12">
        <div class="tabbable tabs-left">
          <ul class="nav nav-tabs">
           <li class="active"><a href="#info" data-toggle="tab">Settings</a></li>
           <li><a href="#motes" data-toggle="tab">Motes</a></li>
           <li><a href="#entry-point" data-toggle="tab">Entry Points</a></li>
           <li><a href="#views" data-toggle="tab">Views</a></li>
            <a id="save-btn" type="button" class="btn" data-loading-text="Saving...">Save</a>
          </ul>

          <div class="tab-content">

          	<div id="info" class="tab-pane fade in active">
              <h4>Project Info</h4>
              <p>Project ID: '._PROJECT_ID_.'</p>
              <p><a href="'.get_bloginfo('wpurl').'/wp-admin/edit-tags.php?taxonomy=dhp_tax_'._PROJECT_ID_.'" >Category Manager</a></p>
          	</div>

            <div id="motes" class="tab-pane fade in">
              <h4>Motes</h4>
              <p>Create relational containers for the data in the custom fields</p>
              <div id="create-mote">
                <p>
                  <input class="span4 mote-name" type="text" name="mote-name" placeholder="Mote Name" />
                </p>
                <p>
                  <select name="custom-fields" class="custom-fields">'.create_custom_field_option_list($dhp_custom_fields).'
                  </select><span class="help-inline">Choose a custom field</span>
                  <label class="checkbox inline">
                    <input type="checkbox" id="pickMultiple" value="multiple"> Multiple
                  </label><div class="btn-group drag-right">
              	<a class="btn btn-info" id="search-replace-btn" data-toggle="modal" href="#projectModal"><i class="icon-edit"></i></a>
              	<a class="btn btn-info" id="delete-cf-btn" data-toggle="modal" href="#projectModal"><i class="icon-trash"></i></a>
              	<a class="btn btn-info" id="create-new-custom" data-toggle="modal" href="#projectModal"><i class="icon-plus"></i></a> 
              </div>                
                </p>
                <p>
                  <select name="cf-type" class="cf-type">                          
                    <option>Text</option>
                    <option>Exact Date</option>
                    <option>Date Range</option>
                    <option>Lat/Lon Coordinates</option>
                    <option>File</option>
                    <option>Image</option>
                  </select><span class="help-inline">Choose a data type</span>
                </p>
                <p><input class="delim" type="text" name="delim" placeholder="Delimiter" /> If multiple text indicate the delimiter</p>
                <p><a class="btn btn-success" id="create-btn">Create mote</a></p>
              </div>           
              <div class="accordion" id="mote-list">                
              </div>              
            </div>

            <div id="entry-point" class="tab-pane fade in">
              <h4>Entry Points</h4>
              <ul id="entryTabs" class="nav nav-tabs">
                <li class="active"><a href="#home" data-toggle="tab">Home</a></li>           
                <li class="dropdown  pull-right">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Create Entry Point<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a id="add-map" >Map</a></li>
                    <li><a id="add-timeline" >Timeline</a></li>
                    <li class="disabled"><a >Topic Cards</a></li>
                    <li><a id="add-transcript" >A/V Transcript</a></li>
                  </ul>
                </li>
              </ul>
              <div id="entryTabContent" class="tab-content">
                <div class="tab-pane fade in active" id="home">
                  <p>Create entry points to the project using the right most tab above. </p>
                </div>               
              </div>
            </div>

            <div id="views" class="tab-pane fade in">
              <h4>Views</h4>
              
              <div class="accordion" id="viewList">
				  <div class="accordion-group">
				    <div class="accordion-heading">
				      <a class="accordion-toggle" data-toggle="collapse" data-parent="#viewList" href="#mapView">
				        Main View
				      </a>
				    </div>
				    <div id="mapView" class="accordion-body collapse in">
				      <div class="accordion-inner">
				       <p>
				       <label class="checkbox">
                    	<input class="save-view map-fullscreen" type="checkbox" name="map-fullscreen" value="fullscreen"> Map Fullscreen
                  		</label>
                  		</p>
                  		<p>
				       <input class="span3 save-view map-width" name="map-width" type="text" placeholder="Width" />             
				       <input class="span3 save-view map-height" name="map-height" type="text" placeholder="Height" />
				       </p>
				       <!--<p>
				       <select name="legend-pos" class="legend-pos save-view">                          
                	    <option>Left</option>
              		    <option>Right</option>
               		   </select><span class="help-inline">Legend Location</span>
               		   </p>-->
				      </div>
				    </div>
				  </div>
				  <div class="accordion-group">
				    <div class="accordion-heading">
				      <a class="accordion-toggle" data-toggle="collapse" data-parent="#viewList" href="#modalView">
				        Modal View
				      </a>
				    </div>
				    <div id="modalView" class="accordion-body collapse">
				      <div class="accordion-inner">
				      	<a href="#projectModal" role="button" class="setup-modal-view btn" data-toggle="modal">
                        	<i class="icon-wrench"></i> Setup Modal
                        </a>
				      </div>
				    </div>
				  </div>
				  <div class="accordion-group">
				    <div class="accordion-heading">
				      <a class="accordion-toggle" data-toggle="collapse" data-parent="#viewList" href="#linkView">
				        Post View
				      </a>
				    </div>
				    <div id="linkView" class="accordion-body collapse">
				      <div class="accordion-inner marker-view">
				      	
				      </div>
				    </div>
				  </div>
				</div>
            </div>
          </div>
        </div>
      </div>  
    </div>
</div>'.
'<select style="display:none;"id="hidden-layers" >'.dhp_build_HTML_maplayer_options(getLayerList()).'</select>'.'
<!--New Custom Field Modal -->
<div id="projectModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>';
} // print_new_bootstrap_html()


// categoryString($cats)
// PURPOSE:	Form list of category names
// INPUT:	$cats = array of category names
// RETURNS: Concatenated string of category names separated by comma
// TO DO:   Can't this be implemented with implode ??

// function categoryString($cats)
// {
// 	$catString;

// 	foreach ($catArray as $key => $cat) {
// 		if($key>0) {
// 			$catString .= ','.$cat;
// 		}
// 		else {
// 			$catString .= $cat;
// 		} 
// 	}
// 	return $catString;
// } // categoryString()


// createParentTerm($term_name,$dhp_tax_name)
// PURPOSE:	Creates top-level term in WP database for a mote taxonomy (may insert or update)
// INPUT:	$term_name = name of mote (must be HTML-encoded)
//			$dhp_tax_name = name of top-level Project taxonomy ("dhp_tax"<pID>)

function createParentTerm($term_name, $dhp_tax_name)
{
	if(term_exists( $term_name, $dhp_tax_name )) {
			$temp_term = get_term_by('name', $term_name, $dhp_tax_name);
			$term_id = $temp_term->id;			
			wp_update_term( $term_id, $dhp_tax_name );
	}
	else {
		wp_insert_term( $term_name, $dhp_tax_name );
	}
} // createParentTerm()


// ====================== AJAX Functions ======================

add_action( 'wp_ajax_dhpSaveProjectSettings', 'dhpSaveProjectSettings' );

// dhpSaveProjectSettings()
// PURPOSE:	Called by JS code on page to save the settings (constructed by JS) for the Project
// ASSUMES:	Project ID encoded in string

function dhpSaveProjectSettings()
{
	$settings =  $_POST['settings'];
	$dhp_projectID = $_POST['project'];

	update_post_meta($dhp_projectID, 'project_settings', $settings);

		// Ajax call must terminate with "die"
	die('working... '. $settings);
} // dhpSaveProjectSettings()


// dhpUpdateTaxonomy($mArray, $mote_name, $dhp_tax_name)
// PURPOSE:	Update the taxonomy 
// INPUT:	$mArray = array of unique values for mote
//			$mote_name = name of mote itself (parent term)
//			$dhp_tax_name = "dhp_tax_"<pID>
// RETURNS:	array of taxonomic terms belonging to $mote_name

function dhpUpdateTaxonomy($mArray, $mote_name, $dhp_tax_name)
{ 
	$term_counts = array_count_values($mArray);	

	$parent_term = get_term_by('name', $mote_name, $dhp_tax_name);
	$parent_id = $parent_term->term_id;
	$args = array('parent' => $parent_id);


	//loop through array and create terms with parent(mote_name)

	foreach ($mArray as &$value) {
   		$termIs = term_exists( $value, $dhp_tax_name, $parent_id ); 	
   		
   		if(!$termIs) {
   			wp_insert_term( $value, $dhp_tax_name, $args );
   		}
   		else {
   			$termName = get_term($termIs->term_id, $dhp_tax_name);
   			// $args = array('parent' => $parent_id, 'alias_of'=>$termName->slug);
   			wp_update_term( $value, $dhp_tax_name, $args );
   		}
	}

		// Gets all top-level parent terms; need "hide_empty=0" because parent terms not associated with any Marker
	$parent_terms_to_exclude = get_terms($dhp_tax_name, 'parent=0&orderby=term_group&hide_empty=0');
	$exclude_string;
	$exclude_count = 0;
		// now concatenate all parent terms (except current parent) in string
	foreach ( $parent_terms_to_exclude as $term ) {
		if($term->term_id != $parent_id) {
			
			if($exclude_count >0) {
				$exclude_string.=',';
			}
			$exclude_string.= $term->term_id;
			$exclude_count = 1;
		}
	}

		// Only get terms in this Project and this Mote parent
	$terms_loaded = get_terms($dhp_tax_name, 'exclude_tree='.$exclude_string.'&orderby=term_group&hide_empty=0');
 	$t_count = count($terms_loaded);

 	//return wp tax id,name,count,order
 	$dhp_top_term = get_term_by('name', $term_name, $dhp_tax_name);

 	if ( $t_count > 0 ){
   		foreach ( $terms_loaded as $term ) {
  	    	$term_url = get_term_meta($term->term_id, 'icon_url', true);
			$term ->icon_url = $term_url;
		}
	}

	return $terms_loaded;
} // dhpUpdateTaxonomy()


// createMoteValueArrays($custom_name, $delim, $project_id)
// PURPOSE: Create arrays of custom field values associated with a project
// INPUT:	$custom_name = name of the custom field (specified by mote) for which we are creating values
//			$delim = character separator for values in field (if any), or null if none
//			$project_id = ID of the Project
// RETURNS:	Array of unique values for the custom field
// TO DO:	A more efficient way of doing this? Sorted array?

function createMoteValueArrays($custom_name, $delim, $project_id)
{
		// Loop through all markers in project
	$moteArray = array();

	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$project_id, 'posts_per_page' => -1 );
	
	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();

		$marker_id = get_the_ID();
		//$temp_post = get_post($marker_id);

			// Get the value in this marker for the custom field
		$tempMoteValue = get_post_meta($marker_id, $custom_name, true);

		if($delim) {
			$tempMoteArray = split($delim,$tempMoteValue);
		}
		else {
			$tempMoteArray = array($tempMoteValue);
		}

		foreach ($tempMoteArray as &$value) {
   		 	array_push($moteArray,$value);
		}
		
	endwhile;

	$result = array_unique($moteArray);

	return $result;
} // createMoteValueArrays()


// creates terms in taxonomy when a legend is created
add_action( 'wp_ajax_dhpCreateLegendTax', 'dhpCreateLegendTax' );

// dhpCreateLegendTax()
// PURPOSE:	Handle Ajax call to create a taxonomy when a Legend is created
// INPUT:	Through $_POST['mote_name'] array: ['type', 'delim', 'custom-fields', 'name']
//			$_POST['project'] = ID of Project
// RETURN:	Array of unique values/tax-terms as JSON object

function dhpCreateLegendTax()
{ 
	$mote = $_POST['mote_name'];
	$mote_type = $mote['type'];
	$mote_delim = $mote['delim'];
	
	$custom_field = $mote['custom-fields'];
	$dhp_projectID = $_POST['project'];

	$dhp_project = get_post($dhp_projectID);
	$dhp_project_slug = $dhp_project->post_name;
	$dhp_tax_name = 'dhp_tax_'.$dhp_project->ID;

	createParentTerm($mote['name'],$dhp_tax_name);
	//get fresh terms from meta feild 

	//returns unique array of values
	$mArray = createMoteValueArrays($custom_field,$mote_delim,$dhp_projectID);

	//create/update terms with mArray
	$terms_loaded = dhpUpdateTaxonomy($mArray, $mote['name'], $dhp_tax_name);

	//die(json_encode($mArray));
	die(json_encode($terms_loaded));
	//die(json_encode($exclude_string));
} // dhpCreateLegendTax()


//Lists all the terms in taxonomies(already created)
add_action( 'wp_ajax_dhpGetMoteValues', 'dhpGetMoteValues' );

// dhpGetMoteValues()
// PURPOSE:	Handle Ajax call to get the unique values for a mote and associate these as
//			taxonomy terms with each Marker post
// INPUT:	$_POST['project'] global is ID of Project
//			$_POST['mote_name'] global is Hash describing mote
// RETURNS:	JSON Object of all of the unique values of the Mote
// TO DO:	Isn't there a lot of duplicate code in here?

function dhpGetMoteValues()
{
	$dhp_projectID = $_POST['project'];
	$mote = $_POST['mote_name'];
	$dhp_tax_name = 'dhp_tax_'.$dhp_projectID;
	$debugArray = array();
	$debugArray['name'] = $mote['name'];
	
		// Loop through markers for this Project, getting values for mote in each marker
		//	and associating the marker with the taxonomic term
	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$dhp_projectID, 'posts_per_page' => -1 );

		// Find all of the terms derived from $mote['name'] in the Project's taxonomy
	$parent_term = get_term_by('name', $mote['name'], $dhp_tax_name);
	$parent_id = $parent_term->term_id;
	$parent_terms_to_exclude = get_terms($dhp_tax_name, 'parent=0&orderby=term_group&hide_empty=0');

	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();
		$marker_id = get_the_ID();
		$tempMoteValue = get_post_meta($marker_id, $mote['custom-fields'], true);
		

		$tempMoteArray = array();
		if($mote['delim']) {
			$tempMoteArray = split( $mote['delim'], $tempMoteValue );
		}
		else {
			$tempMoteArray = array($tempMoteValue);
		}
		$theseTerms = array();
		$debugArray['terms'] = array();
		foreach ($tempMoteArray as &$value) {
			// array_push($debugArray, $value);
			$term = term_exists( $value, $dhp_tax_name, $parent_id ); 	
   		 	if($term) {
   		 		array_push($theseTerms, $term['term_id']);
   		 		array_push($debugArray['terms'], $term['term_id']);
   		 	}
		}
		wp_set_post_terms( $marker_id, $theseTerms, &$dhp_tax_name, true );
	endwhile;

		// Create comma-separated string listing terms derived from other motes
		// TO DO: Push terms to an array rather than form taxonomic string
	$exclude_string;
	$exclude_count = 0;
	foreach ( $parent_terms_to_exclude as $term ) {
		if($term->term_id != $parent_id) {
			
			if($exclude_count >0) {
				$exclude_string.=',';
			}
			$exclude_string.= $term->term_id;
			$exclude_count = 1;
		}
  	    //array_push($exclude_array, $term->term_id);
	}
	$terms_loaded = get_terms($dhp_tax_name, 'exclude_tree='.$exclude_string.'&orderby=term_group&hide_empty=0');
	//$terms = get_terms($dhp_tax_name, array( 'orderby' => 'term_id' ) );
 	$t_count = count($terms_loaded);

 	//return wp tax id,name,count,order
 	//$dhp_top_term = get_term_by('name', $term_name, $dhp_tax_name);
 	if ( $t_count > 0 ){
   		foreach ( $terms_loaded as $term ) {
  	    	$term_url = get_term_meta($term->term_id, 'icon_url', true);
			$term ->icon_url = $term_url;
		}
	}

	die(json_encode($terms_loaded));
	// die(json_encode($debugArray));
	//die(json_encode($dhp_tax_name));
} // dhpGetMoteValues()


// Enable for both editing and viewing

add_action('wp_ajax_dhpGetMarkers', 'dhpGetMarkers' );
add_action('wp_ajax_nopriv_dhpGetMarkers', 'dhpGetMarkers');

// dhpGetMarkers()
// PURPOSE:	Handle Ajax call to get all markers for a Project
// INPUT:	$_POST['project'] is ID of Project
// RETURNS:	JSON object of array of marker values

function dhpGetMarkers()
{
	$dhp_project = $_POST['project'];
	$mArray = createMarkerArray($dhp_project);
	
	die(json_encode($mArray));
} // dhpGetMarkers()


// Enable for both editing and viewing

add_action( 'wp_ajax_dhpGetTimeline', 'dhpGetTimeline' );
add_action( 'wp_ajax_nopriv_dhpGetTimeline', 'dhpGetTimeline' );

// dhpGetTimeline()
// PURPOSE: Handle Ajax call to compute Timeline for Project
// INPUT:	$_POST['project'] is ID of Project
// RETURNS:	Array of timeline data
// TO DO:	Not fully implemented yet

function dhpGetTimeline()
{
	$dhp_project = $_POST['project'];
	$mArray = createTimelineArray($dhp_project);
	
	die(json_encode($mArray));
} // dhpGetTimeline()


// Enable for both editing and viewing

add_action( 'wp_ajax_dhpGetMoteContent', 'dhpGetMoteContent' );
add_action('wp_ajax_nopriv_dhpGetMoteContent', 'dhpGetMoteContent');

// dhpGetMoteContent()
// PURPOSE: Handle Ajax call to fetch the Project-specific data for a specific marker
// INPUT:	$_POST['post'] = ID of marker post
// RETURNS:	JSON object of marker data

function dhpGetMoteContent()
{
	$dhp_post_id = $_POST['post'];

	$post_meta_content = get_post_meta($dhp_post_id);
	die(json_encode($post_meta_content));
} // dhpGetMoteContent()

// Enable for both editing and viewing

add_action( 'wp_ajax_dhpGetTranscriptClip', 'dhpGetTranscriptClip' );
add_action('wp_ajax_nopriv_dhpGetTranscriptClip', 'dhpGetTranscriptClip');

// getTranscriptClip($tran,$clip)
// PURPOSE:	Retrieve section of text file for transcript
// INPUT:	$tran = actual text
//			$clip = String containing from-end time of segment
// RETURNS:	Section of $tran within the time frame specified by $clip

function getTranscriptClip($transcript, $clip)
{
	$codedTransctript = utf8_encode($transcript);
	$clipArray        = split("-", $clip);
	$clipStart        = mb_strpos($codedTransctript, $clipArray[0]);
	$clipEnd          = mb_strpos($codedTransctript, $clipArray[1]);
		// timecode is always 13 characters
	$clipLength       = $clipEnd - $clipStart + 13;

	if( $clipStart && $clipEnd ) {		
		$codedClip  = mb_substr($codedTransctript, $clipStart-1, $clipLength, 'UTF-8');
		$returnClip = utf8_decode($codedClip);
	}
	else {
		$returnClip = json_encode(array('clipStart'=> $clipStart,'clipEnd'=> $clipEnd, 'clipArrayend' => $clipArray[1]));
	}
	return $returnClip;
} // getTranscriptClip()


// loadTranscriptFromFile($fileUrl)
// PURPOSE:	Load the contents of a transcript file
// INPUT:	$fileUrl = the URL to the file
// RETURNS:	The data in file, if successful
// TO DO:	Handle i/o errors

function loadTranscriptFromFile($fileUrl)
{
	$content = @file_get_contents($fileUrl);
	if ($content === false) { /* failure */ } 
	
	else { /* success */ 
		return $content;
	}
} // loadTranscriptFromFile()

// dhpGetTranscriptClip()
// PURPOSE: AJAX function to retrieve section of transcript 
// INPUT:	$_POST['project'] = ID of Project post
//			$_POST['transcript'] = URL to file containing contents of transcript
//			$_POST['timecode'] = timestamp specifying part of transcript to return
// RETURNS:	JSON-encoded section of transcription

function dhpGetTranscriptClip()
{
	$dhp_project = $_POST['project'];
	$dhp_transcript_field = $_POST['transcript'];
	$dhp_clip = $_POST['timecode'];
		// Why is Project post loaded? Does this have a needed side-effect?
	$projectObj = get_post($dhp_project);
	//$dhp_transcript = get_post_meta( $dhp_project, $dhp_project_field, true);
	$dhp_transcript = loadTranscriptFromFile($dhp_transcript_field);
	$dhp_transcript_clip = getTranscriptClip($dhp_transcript,$dhp_clip);

	die(json_encode($dhp_transcript_clip));
} // dhpGetTranscriptClip()

// Enable for both editing and viewing

add_action( 'wp_ajax_dhpGetTranscript', 'dhpGetTranscript' );
add_action( 'wp_ajax_nopriv_dhpGetTranscript', 'dhpGetTranscript');

// dhpGetTranscript()
// PURPOSE: AJAX function to retrieve entire transcript
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['transcript'] = URL to file containing contents of transcript
//			$_POST['tax_view'] = the taxonomic term that the marker matches
// ASSUMES: The transcript is only associated with one taxonomic term
// RETURNS:	JSON-encoded complete transcript

function dhpGetTranscript()
{
	$dhp_project = $_POST['project'];
	$dhp_project_field = $_POST['transcript'];
	//$dhp_clip = $_POST['timecode'];
	$dhp_tax_term = $_POST['tax_view'];
	$projectObj = get_post($dhp_project);
	$dhp_tax_name = 'dhp_tax_'.$projectObj->ID;

	$dhp_settings = json_decode(get_post_meta( $dhp_project, 'project_settings', true),true);
	foreach ($dhp_settings['entry-points'] as $i => $ep) {
 		if (array_key_exists('type', $ep) && $ep['type'] == 'transcript') {
        	$dhp_settings_ep = $dhp_settings['entry-points'][$i];
    		$dhp_audio_mote = getMoteFromName($dhp_settings,$dhp_settings_ep['settings']['audio']);
		}
	}

	$args = array(
		'posts_per_page' => 1,
		'post_type' => 'dhp-markers',
		'tax_query' => array(
			array(
				'taxonomy' => $dhp_tax_name,
				'field' => 'slug',
				'terms' => $dhp_project_field
			)
		)
	);
	$first_marker = get_posts( $args );
	$marker_meta = get_post_meta( $first_marker[0]->ID );
	$dhp_audio_field = getMoteFromName($dhp_settings,$dhp_settings_ep['settings']['audio']);

	$dhp_transcript_field = getMoteFromName($dhp_settings,$dhp_settings_ep['settings']['transcript']);
	$dhp_transcript_cfield = $dhp_transcript_field['custom-fields'];//$marker_meta['transcript_url'])
	
	$dhp_transcript = $marker_meta[$dhp_transcript_cfield][0];
	if($dhp_transcript!='none') {
		$dhp_transcript = loadTranscriptFromFile($marker_meta[$dhp_transcript_cfield][0]);
	}
	$dhp_object;
	//'"'.$dhp_tax_name.','.$dhp_tax_term.'"';//
	$dhp_object['feed'] = dhp_get_group_feed($dhp_tax_name,$dhp_tax_term);
	$dhp_object['settings'] = $dhp_settings_ep;
	$dhp_object['audio'] = $marker_meta[$dhp_audio_field['custom-fields']][0];
	$dhp_object['transcript'] = $dhp_transcript;

		//if project has two transcripts
	if($dhp_settings_ep['settings']['transcript2']) {
		$dhp_transcript2_field = getMoteFromName($dhp_settings,$dhp_settings_ep['settings']['transcript2']);
		$dhp_transcript2_cfield = $dhp_transcript2_field['custom-fields'];//$marker_meta['transcript_url'])
		$dhp_transcript2 = loadTranscriptFromFile($marker_meta[$dhp_transcript2_cfield][0]);
		$dhp_object['transcript2'] = $dhp_transcript2;
	}
	
	die(json_encode($dhp_object));	
} // dhpGetTranscript()


add_action( 'wp_ajax_dhpAddCustomField', 'dhpAddCustomField' );

// dhpAddCustomField()
// PURPOSE:	Handle Ajax call to create new custom field for Project
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['field_name'] = name of new custom field to add
//			$_POST['field_value'] = default value to set in all markers belonging to Project

function dhpAddCustomField()
{
	$dhp_project = $_POST['project'];
	$dhp_custom_field_name = $_POST['field_name'];
	$dhp_custom_field_value = $_POST['field_value'];

	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$dhp_project, 'posts_per_page' => -1 );
	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();

		$marker_id = get_the_ID();
		add_post_meta($marker_id, $dhp_custom_field_name, $dhp_custom_field_value, true);
				
	endwhile;
	
	die();
} // dhpAddCustomField()


add_action( 'wp_ajax_dhpCreateCustomFieldFilter', 'dhpCreateCustomFieldFilter' );

// dhpCreateCustomFieldFilter()
// PURPOSE: Handle Ajax call to add the value of custom fields that match "filter condition"
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['field_name'] = name of custom field
//			$_POST['field_value'] = value to set of custom field
//			$_POST['filter_key'] = name of field on which to match
//			$_POST['filter_value'] = value of field to match
// TO DO:	Rename function! dhpSetFieldByCustomFieldFilter?

function dhpCreateCustomFieldFilter()
{
	$dhp_project 			= $_POST['project'];
	$dhp_custom_field_name 	= $_POST['field_name'];
	$dhp_custom_field_value	= $_POST['field_value'];
	$dhp_custom_filter_key 	= $_POST['filter_key'];
	$dhp_custom_filter_value = $_POST['filter_value'];

	$args = array( 
		'post_type' => 'dhp-markers', 
		'posts_per_page' => -1,
		'meta_query' => array(
			'relation' => 'AND',
			array(
				'key' => 'project_id',
				'value' => $dhp_project
			),
			array(
				'key' => $dhp_custom_filter_key,
				'value' => $dhp_custom_filter_value
			)
		)
	);

	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();

		$marker_id = get_the_ID();
		add_post_meta($marker_id, $dhp_custom_field_name, $dhp_custom_field_value, true);
				
	endwhile;
	
	die();
} // dhpCreateCustomFieldFilter()


add_action('wp_ajax_dhpUpdateCustomFieldFilter', 'dhpUpdateCustomFieldFilter');

// dhpUpdateCustomFieldFilter()
// PURPOSE: To modify the value of a field (based on string replace) in all of a Project's Markers if
//			it satisfies query condition and currently matches a certain value (like Find & Replace)
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['field_name'] = name of custom field we wish to change
//			$_POST['current_value'] = custom field must have this field to be changed
//			$_POST['new_value'] = new value to set
//			$_POST['filter_key'] = custom field upon which search/filter is based
//			$_POST['filter_value'] = value that must be in custom field
// RETURNS:	Number of markers whose values were changed
// TO DO:	Reduce redundant code with other nearby functions

function dhpUpdateCustomFieldFilter()
{
	$dhp_project 				= $_POST['project'];
	$dhp_custom_field_name		= $_POST['field_name'];
	$dhp_custom_current_value	= $_POST['current_value'];
	$dhp_custom_new_value		= $_POST['new_value'];
	$dhp_custom_filter_key		= $_POST['filter_key'];
	$dhp_custom_filter_value 	= $_POST['filter_value'];

	$args = array( 
		'post_type' => 'dhp-markers', 
		'posts_per_page' => -1,
		'meta_query' => array(
			'relation' => 'AND',
			array(
				'key' => 'project_id',
				'value' => $dhp_project
			),
			array(
				'key' => $dhp_custom_filter_key,
				'value' => $dhp_custom_filter_value
			)
		)
	);
	$dhp_count=0;
	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();
		$dhp_count++;
		$marker_id = get_the_ID();
		$tempPostContent = get_the_content();
		if($dhp_custom_field_name=='the_content') {

			$new_value = str_replace($dhp_custom_current_value,$dhp_custom_new_value,$tempPostContent);
			
			$new_post = array();
			$new_post['ID'] = $marker_id;
			$new_post['post_content'] = $new_value;
			wp_update_post( $new_post );
		}
		else {
			$temp_value = get_post_meta( $marker_id, $dhp_custom_field_name, true );
			//replaces string within the value not the whole value
			$new_value = str_replace($dhp_custom_current_value, $dhp_custom_new_value, $temp_value);
			update_post_meta($marker_id, $dhp_custom_field_name, $new_value);
		}
	endwhile;
	
	die(json_encode($dhp_count));
} // dhpUpdateCustomFieldFilter()


add_action( 'wp_ajax_dhpReplaceCustomFieldFilter', 'dhpReplaceCustomFieldFilter' );

// dhpReplaceCustomFieldFilter()
// PURPOSE: To replace the value of a field in all of a Project's Markers if
//			it satisfies query condition and currently matches a certain value
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['field_name'] = name of custom field we wish to change
//			$_POST['new_value'] = value to 
//			$_POST['filter_key'] = custom field upon which search/filter is based
//			$_POST['filter_value'] = value that must be in custom field
// RETURNS:	Number of markers whose values were changed
// TO DO:	Reduce redundant code with other nearby functions

function dhpReplaceCustomFieldFilter()
{
	$dhp_project 				= $_POST['project'];
	$dhp_custom_field_name		= $_POST['field_name'];
	$dhp_custom_new_value		= $_POST['new_value'];
	$dhp_custom_filter_key		= $_POST['filter_key'];
	$dhp_custom_filter_value 	= $_POST['filter_value'];

	$args = array( 
		'post_type' => 'dhp-markers', 
		'posts_per_page' => -1,
		'meta_query' => array(
			'relation' => 'AND',
			array(
				'key' => 'project_id',
				'value' => $dhp_project
			),
			array(
				'key' => $dhp_custom_filter_key,
				'value' => $dhp_custom_filter_value
			)
		)
	);
	$dhp_count=0;
	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();
		$dhp_count++;
		$marker_id = get_the_ID();
		$tempPostContent = get_the_content();
		if($dhp_custom_field_name=='the_content') {
			$new_value = $dhp_custom_new_value;
			
			$new_post = array();
			$new_post['ID'] = $marker_id;
			$new_post['post_content'] = $new_value;
			wp_update_post( $new_post );
		}
		else {
			$temp_value = get_post_meta( $marker_id, $dhp_custom_field_name, true );
			//replaces string within the value not the whole value
			$new_value = $dhp_custom_new_value;
			update_post_meta($marker_id, $dhp_custom_field_name, $new_value);
		}
	endwhile;
	
	die(json_encode($dhp_count));
} // dhpReplaceCustomFieldFilter()


add_action( 'wp_ajax_dhpGetFieldValues', 'dhpGetFieldValues' );

// dhpGetFieldValues()
// PURPOSE: Handle Ajax call to get values for custom field
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['field_name'] = name of custom field
// RETURNS:	JSON Object of array of all unique values for the field in the project
// TO DO:	Rename function

function dhpGetFieldValues()
{
	$dhp_project 			= $_POST['project'];
	$dhp_custom_field_name 	= $_POST['field_name'];
	$tempValues = createMetaValueArray($dhp_custom_field_name, $dhp_project);

	die(json_encode($tempValues));
} // dhpGetFieldValues()


add_action( 'wp_ajax_dhpFindReplaceCustomField', 'dhpFindReplaceCustomField' );

// dhpFindReplaceCustomField()
// PURPOSE: Handle Ajax function to do string replace on matching values in all custom fields in Project
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['field_name'] = name of custom field
//			$_POST['find_value'] = field must match this value to be replaced
//			$_POST['replace_value'] = value to use for string replace in field
// RETURNS:	Number of markers whose values were changed
// TO DO:	Reduce redundant code!

function dhpFindReplaceCustomField()
{
	$dhp_project = $_POST['project'];
	$dhp_custom_field_name = $_POST['field_name'];
	$dhp_custom_find_value = $_POST['find_value'];
	$dhp_custom_replace_value = $_POST['replace_value'];

	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$dhp_project, 'posts_per_page' => -1 );
	$loop = new WP_Query( $args );
	$dhp_count=0;
	while ( $loop->have_posts() ) : $loop->the_post();
		$dhp_count++;
		$marker_id = get_the_ID();
		$tempPostContent = get_the_content();
		if($dhp_custom_field_name=='the_content') {
			$new_value = str_replace($dhp_custom_find_value,$dhp_custom_replace_value,$tempPostContent);
			
			$new_post = array();
			$new_post['ID'] = $marker_id;
			$new_post['post_content'] = $new_value;
			wp_update_post( $new_post );
		}
		else {
			$temp_value = get_post_meta( $marker_id, $dhp_custom_field_name, true );
			//replaces string within the value not the whole value
			$new_value = str_replace($dhp_custom_find_value,$dhp_custom_replace_value,$temp_value);
			update_post_meta($marker_id, $dhp_custom_field_name, $new_value);
		}
		
	endwhile;
	
	die(json_encode($dhp_count));
} // dhpFindReplaceCustomField()


add_action( 'wp_ajax_dhpDeleteCustomField', 'dhpDeleteCustomField' );

// dhpDeleteCustomField()
// PURPOSE:	Handle Ajax query to remove specific custom field from all markers of a Project
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['field_name'] = name of custom field

function dhpDeleteCustomField()
{
	$dhp_project = $_POST['project'];
	$dhp_custom_field_name = $_POST['field_name'];
	
	$args = array( 'post_type' => 'dhp-markers', 'meta_key' => 'project_id','meta_value'=>$dhp_project, 'posts_per_page' => -1 );
	$loop = new WP_Query( $args );
	while ( $loop->have_posts() ) : $loop->the_post();

		$marker_id = get_the_ID();
		delete_post_meta($marker_id, $dhp_custom_field_name);
		//add_post_meta($marker_id, $dhp_custom_field_name, $dhp_custom_field_value, true);
				
	endwhile;
	
	die();
} // dhpDeleteCustomField()


add_action( 'wp_ajax_dhpCreateTaxTerms', 'dhpCreateTaxTerms' );

// dhpCreateTaxTerms()
// PURPOSE:	Handle Ajax function to create all terms associated with all of the values defined
//			by a mote in a Project (Saving results of Configure Legend function)
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['mote_name'] = name of mote
//			$_POST['terms'] = array of mote/legend values
// RETURNS:	JSON Object version of loopTermHeirarchy() result

function dhpCreateTaxTerms()
{
	$mote_parent = $_POST['mote_name'];
	$dhp_projectID = $_POST['project'];
	$dhp_project_terms = stripslashes($_POST['terms']);

	$dhp_project_terms1 = json_decode($dhp_project_terms);
	$termDetailsArray = array('parentTerm'=>$mote_parent, 'projectID' => $dhp_projectID, 'termsArray'=>$dhp_project_terms1);

	$newArgs = loopTermHeirarchy($termDetailsArray);

	die(json_encode($newArgs));
} // dhpCreateTaxTerms()


// loopTermHeirarchy($argArray)
// PURPOSE: Saving taxonomy hierarchy in WP and updating display of icon URL
// INPUT:	$argArray['parentTerm'] = name of parent mote
//			$argArray['projectID'] = ID of Project
//			$argArray['termsArray'] = array of taxonomy terms
// RETURNS:	Hash: ['parentTerm'] = $mote_parent, ['projectID'], ['termsArray'] = array of taxonomy terms, ['count'] = size of terms array

function loopTermHeirarchy($argArray)
{
	$mote_parent = $argArray['parentTerm'];
	//convert mote_parent to id
	
	$dhp_project_terms = $argArray['termsArray'];
	$dhp_tax_name = 'dhp_tax_'.$argArray['projectID'];
	$mote_parentID = get_term_by('name', $mote_parent, $dhp_tax_name);
	$meta_key = 'icon_url';
	$myCount = count($dhp_project_terms);

	foreach ($dhp_project_terms as $term) {
		$term_name = $term->name;
		$parent_term_id = $term->parent;
		$term_id = $term->term_id;
		$term_order = $term->term_order;
		$meta_value = $term->icon_url;

		if($meta_value=='undefined') { $meta_value = '';}
		
		if( ($parent_term_id==0||$parent_term_id==""||$parent_term_id==null) && ($term_id!=$mote_parent) ) {
			$parent_term_id = $mote_parent;
		}

		$args = array( 'parent' => $parent_term_id,'term_group' =>  $term_order );
		//update term(insert takes place on legend setup)
		wp_update_term( $term_id, $dhp_tax_name, $args );
		//clear out old icon and insert new icon
		// TO DO: just update_term_meta
		delete_term_meta($term_id, $meta_key);
		add_term_meta($term_id, $meta_key, $meta_value);
		
	}
	$oldArgs = array('parentTerm'=>$mote_parent, 'projectID' => $argArray['projectID'], 'termsArray'=>$dhp_project_terms, 'count'=> $myCount);
	return $oldArgs;
} // loopTermHeirarchy()


add_action( 'wp_ajax_dhpCreateTermInTax', 'dhpCreateTermInTax' );

// dhpCreateTermInTax()
// PURPOSE:	Handle adding new terms to taxonomy (that don't pre-exist in Marker data)
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['term_name'] = name of taxonomy term to add
//			$_POST['parent_term_name'] = name of parent term under which it should be added
// RETURNS:	JSON Object describing new term
// TO DO:	Better error handling?

function dhpCreateTermInTax()
{
	$dhp_projectID 		= $_POST['project'];
	$dhp_term_name		= $_POST['term_name'];
	$parent_term_name	= $_POST['parent_term_name'];

	$dhp_tax_name = 'dhp_tax_'.$dhp_projectID;
	$parent_term = term_exists( $parent_term_name, $dhp_tax_name );
		// TO DO: Check and handle non-existing term?

	$parent_term_id = $parent_term['term_id'];
	$args = array( 'parent' => $parent_term_id );
	//create new term
	wp_insert_term( $dhp_term_name, $dhp_tax_name, $args );
	$newTerm = get_term_by('name', $dhp_term_name, $dhp_tax_name);

	die(json_encode($newTerm));
} // dhpCreateTermInTax()


add_action( 'wp_ajax_dhpDeleteTerms', 'dhpDeleteTerms' );

// dhpDeleteTerms()
// PURPOSE:	Delete taxonomic terms in Project and all terms derived from it (as parent)
// INPUT:	$_POST['project'] = ID of Project
//			$_POST['term_name'] = name of taxonomy term to delete
// RETURNS:	Array of all children that were deleted

function dhpDeleteTerms()
{
	$dhp_projectID = $_POST['project'];
	$dhp_term_name = $_POST['term_name'];
	$dhp_project = get_post($dhp_projectID);
	$dhp_project_slug = $dhp_project->post_name;
	
	$dhp_tax = 'dhp_tax_'.$dhp_projectID;
	//get term id, get children term ids
	$dhp_delete_parent_term = get_term_by('name',$dhp_term_name,$dhp_tax);
	$dhp_delete_parent_id = $dhp_delete_parent_term->term_id;
	$dhp_delete_children = get_term_children($dhp_delete_parent_id,$dhp_tax);
	foreach ($dhp_delete_children as $delete_term) {
		wp_delete_term($delete_term, $dhp_tax);
	}
	wp_delete_term($dhp_delete_parent_id, $dhp_tax);

	die(json_encode($dhp_delete_children));
} // dhpDeleteTerms()


add_action( 'wp_ajax_dhpGetCustomFields', 'dhpGetCustomFields' );

// dhpGetCustomFields()
// PURPOSE:	Handle Ajax call to retrieve all custom fields defined for a Project
// INPUT:	$_POST['project'] = ID of Project
// RETURNS: JSON Object of array of all custom fields

function dhpGetCustomFields()
{
	$dhp_projectID = $_POST['project'];	
	
	$dhp_custom_fields = createUniqueCustomFieldArray($dhp_projectID);
	die(json_encode($dhp_custom_fields));
} // dhpGetCustomFields()


add_action( 'wp_restore_post_revision', 'dhp_project_restore_revision', 10, 2 );

// dhp_project_restore_revision( $post_id, $revision_id )
// PURPOSE: Handles returning to an earlier revision of this post
// INPUT:	$post_id = ID of original post
//			$revision_id = ID of new revised post
// ASSUMES:	$dhp_project_settings_fields global is set

function dhp_project_restore_revision( $post_id, $revision_id )
{
	global $dhp_project_settings_fields;

	$post     = get_post( $post_id );
	$revision = get_post( $revision_id );
	foreach ($dhp_project_settings_fields as $field) {
			$old = get_metadata( 'post', $revision->ID, $field['id'], true);
			if ( false !== $old) {
				update_post_meta($post_id, $field['id'], $old);
			} else {
				delete_post_meta($post_id, $field['id'] );
			}
		} // end foreach
} // dhp_project_restore_revision()


//add_filter( '_wp_post_revision_fields', 'my_plugin_revision_fields' );
// function my_plugin_revision_fields( $fields )
// {
// 	$fields['my_meta'] = 'My Meta';
// 	return $fields;
// } // my_plugin_revision_fields()

//add_filter( '_wp_post_revision_field_my_meta', 'my_plugin_revision_field', 10, 2 );
// function my_plugin_revision_field( $value, $field )
// {
// 	global $revision;
// 	return get_metadata( 'post', $revision->ID, $field, true );
// } // my_plugin_revision_field()


// dhp_get_type_settings($typeName, $epList)
// RETURNS: Settings for entry point whose type is typeName in epList
// ASSUMES:	The type is definitely contained in object

function dhp_get_type_settings($typeName, $epList)
{
	foreach($epList as $eps) {
		if($eps['type'] == $typeName){
			return $eps['settings'];
		}
	}
} // dhp_get_type_settings()


// dhp_get_map_type($typeName,$layerList)
// RETURNS: Map type ID for layer whose type is typeName in epList
// ASSUMES:	The type is definitely contained in object

function dhp_get_map_type($typeName,$layerList)
{
	foreach($layerList as $layer) {
		if($layer['mapType'] == $typeName) {
			$map_id = get_post_meta($layer['id'],'dhp_map_typeid');
			return $map_id[0];
		}
	}
} // dhp_get_map_type()


add_action( 'admin_enqueue_scripts', 'add_dhp_project_admin_scripts', 10, 1 );

// add_dhp_project_admin_scripts( $hook )
// Custom scripts to be run on Project new/edit pages only
// PURPOSE: Prepare CSS and JS files for all page types in WP
// INPUT:	$hook = name of template file being loaded
// ASSUMES:	Other WP global variables for current page are set
//			$layers_global has been set by init process

function add_dhp_project_admin_scripts( $hook )
{
    global $post;
    global $layers_global;

    $blog_id = get_current_blog_id();
	$dev_url = get_admin_url( $blog_id ,'admin-ajax.php');

    //$dhp_custom_fields = createUniqueCustomFieldArray($post->ID);

 		// Editing a specific project in admin panel
    if ( $hook == 'post-new.php' || $hook == 'post.php' ) {
        if ( 'project' === $post->post_type ) {    
        	$tempLayers = 'layers '.$layers_global;
			//wp_register_style( 'ol-style', plugins_url('/js/OpenLayers/theme/default/style.css',  dirname(__FILE__) ));
			//wp_enqueue_style( 'ol-map', plugins_url('/css/ol-map.css',  dirname(__FILE__) ));
			
			wp_enqueue_style( 'dhp-sortable-style', plugins_url('/css/sortable.css',  dirname(__FILE__) ));
			wp_enqueue_style( 'dhp-bootstrap-style', plugins_url('/lib/bootstrap/css/bootstrap.min.css',  dirname(__FILE__) ));
			wp_enqueue_style( 'dhp-bootstrap-responsive-style', plugins_url('/lib/bootstrap/css/bootstrap-responsive.min.css',  dirname(__FILE__) ));
			wp_enqueue_style( 'dhp-jquery-ui-style', 'http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css');
			//wp_enqueue_style( 'dhp-bootstrap-slider-style', plugins_url('/lib/bootstrap/css/slider.css',  dirname(__FILE__) ));
			wp_enqueue_style( 'dhp-style', plugins_url('/css/dhp-style.css',  dirname(__FILE__) ));
			
			// wp_enqueue_script( 'jquery' );
			// wp_enqueue_script( 'jquery-ui' );

				// There is a conflict between default jQuery and nestedSortable, so we must replace it with a different
				//	version of jQuery
			wp_dequeue_script( 'jquery' ); 
			wp_dequeue_script( 'jquery-ui' );
			wp_enqueue_script(  'dhp-jquery', plugins_url('/lib/jquery-1.7.2.min.js', dirname(__FILE__) ));
			wp_enqueue_script(  'dhp-jquery-ui', plugins_url('/lib/jquery-ui-1.8.16.custom.min.js', dirname(__FILE__) ));

	 		wp_enqueue_script( 'jquery-ui-slider' );
			wp_enqueue_script(  'dhp-bootstrap', plugins_url('/lib/bootstrap/js/bootstrap.min.js', dirname(__FILE__) ),'jquery');
			//wp_enqueue_script(  'bootstrap-button-fix', plugins_url('/lib/bootstrap/js/bootstrap-button-fix.js', dirname(__FILE__) ),'dhp-bootstrap');
			//wp_enqueue_script(  'dhp-bootstrap-slider', plugins_url('/lib/bootstrap/js/bootstrap-slider.js', dirname(__FILE__) ),'dhp-bootstrap');
           	
			wp_enqueue_script(  'dhp-touch-punch', plugins_url('/lib/jquery.ui.touch-punch.js', dirname(__FILE__) ));
            wp_enqueue_script( 'open-layers', plugins_url('/js/OpenLayers/OpenLayers.js', dirname(__FILE__) ));
        
             //wp_enqueue_script(  'open-layers', plugins_url('/js/OpenLayers/OpenLayers.js', dirname(__FILE__) ));
			wp_enqueue_script(  'dhp-nested-sortable', plugins_url('/lib/jquery.mjs.nestedSortable.js', dirname(__FILE__) ));
			wp_enqueue_style( 'dhp-jPicker-style1', plugins_url('/js/jpicker/css/jPicker-1.1.6.min.css',  dirname(__FILE__) ));
			wp_enqueue_style( 'dhp-jPicker-style2', plugins_url('/js/jpicker/jPicker.css',  dirname(__FILE__) ));
			wp_enqueue_script(  'dhp-jPicker', plugins_url('/js/jpicker/jpicker-1.1.6.js', dirname(__FILE__) ));

			wp_enqueue_script(  'dhp-project-script', plugins_url('/js/dhp-project-admin.js', dirname(__FILE__) ));
			wp_localize_script( 'dhp-project-script', 'dhpDataLib', array(
				'ajax_url' => __($dev_url, 'dhp'),
				//'dhp_custom_fields' => __($dhp_custom_fields, 'dhp'),
				'layers' => __($tempLayers, 'dhp')
			) );
        }

        // Shows list of all Project in admin panel
    } else if ( $hook == 'edit.php'  ) {
        if ( 'project' === $post->post_type ) {     
			//wp_register_style( 'ol-style', plugins_url('/js/OpenLayers/theme/default/style.css',  dirname(__FILE__) ));
			wp_enqueue_style( 'ol-map', plugins_url('/css/ol-map.css',  dirname(__FILE__) ));
			wp_enqueue_script(  'jquery' );
             //wp_enqueue_script(  'open-layers', plugins_url('/js/OpenLayers/OpenLayers.js', dirname(__FILE__) ));
			 //wp_enqueue_script(  'dhp-project-script2', plugins_url('/js/dhp-project-admin2.js', dirname(__FILE__) ));
        }
    }
} // add_dhp_project_admin_scripts()

// dhp_register_maps($mapLayers)
// PURPOSE: Prepare required scripts for maps to be rendered as WP content
// INPUT:	$mapLayers = array of map layers (each containing Hash ['mapType'], ['id'])
// ASSUMES:	Map data has been loaded into WP DB
// TO DO:	Better error handling if map data doesn't exist?

function dhp_register_maps($mapLayers)
{
	//if cdla, load api
	wp_register_script(
				'cdlaMaps',
				'http://docsouth.unc.edu/cdlamaps/api/OASIS',
				array( 'open-layers' ),
				false,
				true
			);
	//loop thru layers
	$cdla_count = 0;
	foreach($mapLayers as $layer) {
		//var $ec = $eps.type;
		//return $layer['id'];
		if($layer['mapType'] == 'type-CDLA')
		{
			$map_id = get_post_meta($layer['id'],'dhp_map_typeid',true);
			$cdla_layer_url = 'http://docsouth.unc.edu/cdlamaps/api/mapdata/OASIS/'.$map_id;
			
			wp_register_script(
				'cdla-layer-data'.$cdla_count,
				$cdla_layer_url,
				array( 'cdlaMaps' ),
				false,
				true
			);
			wp_enqueue_script( 'cdla-layer-data'.$cdla_count);
			$cdla_count++;
		}
		//return $ec;
	}	
} // dhp_register_maps()


add_filter( 'single_template', 'dhp_page_template' );

// dhp_page_template( $page_template )
// PURPOSE:	Called by WP to modify output for rendering page, inc template to be used, acc to Project
// INPUT:	$page_template = default path to file to use for template to render page
// ASSUMES:	WP global variables for current post set correctly
// RETURNS:	Modified $page_template setting (file path to new php template file)
// TO DO:	Only enqueue styles and scripts for the visualization actually used (map, timeline, etc.)

function dhp_page_template( $page_template )
{
	global $post;

	$blog_id = get_current_blog_id();
	$dev_url = get_admin_url( $blog_id ,'admin-ajax.php');
	$post_type = get_query_var('post_type');


		// Viewing a Project?
    if ( $post_type == 'project' ) {
    	$projectSettings_get = get_post_meta($post->ID, 'project_settings');
    	$projectSettings = json_decode($projectSettings_get[0],true);
    	$projectSettings_map = dhp_get_type_settings('map',$projectSettings['entry-points']);

    	//if map type is cdla get id
    	$projectSettings_map_cdla = dhp_get_map_type('type-CDLA',$projectSettings_map['layers']);

		dhp_register_maps($projectSettings_map['layers']);

    	wp_register_script(
				'cdlaMaps',
				'http://docsouth.unc.edu/cdlamaps/api/OASIS',
				array( 'open-layers' ),
				false,
				true
			);	
    	
        $page_template = dirname( __FILE__ ) . '/dhp-project-template.php';

		wp_enqueue_style( 'dhp-bootstrap-style', plugins_url('/lib/bootstrap/css/bootstrap.min.css',  dirname(__FILE__) ));
		wp_enqueue_style( 'dhp-bootstrap-responsive-style', plugins_url('/lib/bootstrap/css/bootstrap-responsive.min.css',  dirname(__FILE__) ));
        wp_enqueue_style( 'dhp-jquery-ui-style', 'http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css');
		wp_enqueue_style( 'ol-map', plugins_url('/css/ol-map.css',  dirname(__FILE__) ));
		wp_enqueue_style( 'joyride', plugins_url('/css/joyride-2.1.css',  dirname(__FILE__) ));
			
		wp_enqueue_script('jquery');
		wp_enqueue_script( 'jquery-ui' );
		wp_enqueue_script(  'dhp-jquery-ui', plugins_url('/lib/jquery-ui-1.10.3.custom.min.js', dirname(__FILE__) ));
 		wp_enqueue_script( 'jquery-ui-slider' );
			
		wp_enqueue_script( 'dhp-bootstrap', plugins_url('/lib/bootstrap/js/bootstrap.min.js', dirname(__FILE__) ),'jquery');
			
		wp_enqueue_script( 'joyride', plugins_url('/js/jquery.joyride-2.1.js', dirname(__FILE__),array('jquery') ));


		wp_enqueue_script('underscore');
		//wp_enqueue_script( 'open-layers', 'http://dev.openlayers.org/releases/OpenLayers-2.12/lib/OpenLayers.js' );
    	wp_enqueue_script( 'open-layers', plugins_url('/js/OpenLayers/OpenLayers.js', dirname(__FILE__) ));
    	wp_enqueue_script( 'dhp-google-map-script', 'http'. ( is_ssl() ? 's' : '' ) .'://maps.google.com/maps/api/js?v=3&amp;sensor=false');
        wp_enqueue_script( 'soundcloud-api', 'http://w.soundcloud.com/player/api.js','jquery');
    	wp_enqueue_script( 'cdlaMaps' );

    	if($projectSettings_map_cdla) {
    		//wp_enqueue_script( 'cdla-layer-data' );
    	}

        wp_enqueue_script( 'timeline-js', plugins_url('/js/storyjs-embed.js', dirname(__FILE__) ));

		wp_enqueue_script( 'dhp-public-project-script', plugins_url('/js/dhp-project-page.js', dirname(__FILE__) ),'mediaelement');
		 
		wp_localize_script( 'dhp-public-project-script', 'dhpData', array(
			'ajax_url' => __($dev_url, 'dhp'),
			'settings' => __($projectSettings_get[0], 'dhp'),
			'map' => __($projectSettings_map, 'dhp'),
			'layers' => __($projectSettings_map['layers'], 'dhp')
		) );

		// Looking at a Marker/Data entry?
    } else if ( $post_type == 'dhp-markers' ) {
		$projectSettings_id = get_post_meta($post->ID, 'project_id',true);
		$projectSettings_get = get_post_meta($projectSettings_id, 'project_settings');
    	$projectSettings = json_decode($projectSettings_get[0],true);
    	$projectSettings_map = dhp_get_type_settings('map',$projectSettings['entry-points']);

    	//if map type is cdla get id
    	$projectSettings_map_cdla = dhp_get_map_type('type-CDLA',$projectSettings_map['layers']);

		dhp_register_maps($projectSettings_map['layers']);

    	wp_register_script(
				'cdlaMaps',
				'http://docsouth.unc.edu/cdlamaps/api/OASIS',
				array( 'open-layers' ),
				false,
				true
			);	
    	
        $page_template = dirname( __FILE__ ) . '/dhp-project-template.php';

		wp_enqueue_style( 'dhp-bootstrap-style', plugins_url('/lib/bootstrap/css/bootstrap.min.css',  dirname(__FILE__) ));
		wp_enqueue_style( 'dhp-bootstrap-responsive-style', plugins_url('/lib/bootstrap/css/bootstrap-responsive.min.css',  dirname(__FILE__) ));

		wp_enqueue_style( 'ol-map', plugins_url('/css/ol-map.css',  dirname(__FILE__) ));
		wp_enqueue_style( 'joyride', plugins_url('/css/joyride-2.1.css',  dirname(__FILE__) ));	
		wp_enqueue_script('jquery');

			
		wp_enqueue_script( 'dhp-bootstrap', plugins_url('/lib/bootstrap/js/bootstrap.min.js', dirname(__FILE__) ),'jquery');
			
		//wp_enqueue_script( 'mediaelement', plugins_url('/js/mediaelement/mediaelement-and-player.min.js', dirname(__FILE__),array('jquery') ));
		wp_enqueue_script('underscore');

		//wp_enqueue_script( 'open-layers', 'http://dev.openlayers.org/releases/OpenLayers-2.12/lib/OpenLayers.js' );
    	wp_enqueue_script( 'open-layers', plugins_url('/js/OpenLayers/OpenLayers.js', dirname(__FILE__) ));
    	wp_enqueue_script( 'dhp-google-map-script', 'http'. ( is_ssl() ? 's' : '' ) .'://maps.google.com/maps/api/js?v=3&amp;sensor=false');

    	wp_enqueue_script( 'cdlaMaps' );
        //wp_enqueue_script( 'timeline-js', plugins_url('/js/storyjs-embed.js', dirname(__FILE__) ));

		wp_enqueue_script( 'dhp-public-project-script', plugins_url('/js/dhp-marker-page.js', dirname(__FILE__) ),'jquery');
		 
		wp_localize_script( 'dhp-public-project-script', 'dhpData', array(
			'ajax_url' => __($dev_url, 'dhp'),
			'settings' => __($projectSettings_get[0], 'dhp'),
			'map' => __($projectSettings_map, 'dhp'),
			'layers' => __($projectSettings_map['layers'], 'dhp')
		) );
    }
    return $page_template;
} // dhp_page_template()


add_filter( 'archive_template', 'dhp_tax_template' );

// dhp_tax_template( $page_template )
// PURPOSE: Set template to be used to show results of top-level custom taxonomy display
// INPUT:	$page_template = default path to file to use for template to render page
// RETURNS:	Modified $page_template setting (file path to new php template file)
// TO DO:   Only enqueue the styles/scripts actually used for the visualization/interface

function dhp_tax_template( $page_template )
{
	$blog_id = get_current_blog_id();
	$dev_url = get_admin_url( $blog_id ,'admin-ajax.php');

		// ensure a Taxonomy archive page is being rendered
	if( is_tax() ) {
	    global $wp_query;

	    $term = $wp_query->get_queried_object();
	    $title = $term->taxonomy;
	    $term_parent = get_term($term->parent, $title);

	    	// Get the name of the term, which is also the name of the custom field
	    $term->parent_name = $term_parent->name;

	    // $page_template = dirname( __FILE__ ) . '/dhp-archive.php';
	    //get mp3 url from first term marker
	    //get transcript url

	    	// Get Project name by removing prefix from taxonomy name
	    $pieces = explode("dhp_tax_", $title);
	    	// Retrieve ID from Project post
	    $projectID = $pieces[1];
	    	// Retrieve Project's settings
	    $project_settings = get_post_meta($projectID,'project_settings',true);

	    	// mediaelement for timelines -- not currently used
		// wp_enqueue_style('mediaelement', plugins_url('/js/mediaelement/mediaelementplayer.css',  dirname(__FILE__) ));

		wp_enqueue_style( 'dhp-bootstrap-style', plugins_url('/lib/bootstrap/css/bootstrap.min.css',  dirname(__FILE__) ));
		wp_enqueue_style( 'dhp-bootstrap-responsive-style', plugins_url('/lib/bootstrap/css/bootstrap-responsive.min.css',  dirname(__FILE__) ));
	    wp_enqueue_script( 'soundcloud-api', 'http://w.soundcloud.com/player/api.js','jquery');
	    wp_enqueue_style( 'ol-map', plugins_url('/css/ol-map.css',  dirname(__FILE__) ));
	    wp_enqueue_style( 'joyride', plugins_url('/css/joyride-2.1.css',  dirname(__FILE__) ));
		//map reqs	
	    wp_enqueue_script( 'open-layers', plugins_url('/js/OpenLayers/OpenLayers.js', dirname(__FILE__) ));
	    wp_enqueue_script( 'cdlaMaps' );
		if($projectSettings_map_cdla) {
	    	wp_enqueue_script( 'cdla-layer-data' );
	    }
		//$projectSettings_get = get_post_meta($post->ID, 'project_settings');
		
		wp_enqueue_script( 'jquery' );
		wp_enqueue_script( 'dhp-bootstrap', plugins_url('/lib/bootstrap/js/bootstrap.min.js', dirname(__FILE__) ),'jquery');		
		wp_enqueue_script( 'underscore' );
		wp_enqueue_script( 'joyride', plugins_url('/js/jquery.joyride-2.1.js', dirname(__FILE__),array('jquery') ));
			
		wp_enqueue_script( 'dhp-tax-script', plugins_url('/js/dhp-tax-template.js', dirname(__FILE__) ));
		
		wp_localize_script( 'dhp-tax-script', 'dhpData', array(
				'project_id' => __($projectID,'dhp'),
				'ajax_url' => __($dev_url, 'dhp'),
				'tax' => __($term,'dhp'), 
				'project_settings' => __($project_settings)
				
			) );
	}
	return $page_template;
} // dhp_tax_template()

// dhp_deploy_icons()
// PURPOSE:	Produce HTML to display all marker icons in sidebar; search for all gif, jpg and png files

// function dhp_deploy_icons()
// { 	
// 	$icon_path = DHP_PLUGIN_URL.'/images/icons/';
// 	$icon_dir = DHP_PLUGIN_DIR.'/images/icons/';	
	
// 	$icons_array = array();
	
	
// 	if ($handle = opendir($icon_dir)) {
		
// 		while (false !== ($file = readdir($handle))) {
	
// 			$file_type = wp_check_filetype($file);
	
// 			$file_ext = $file_type['ext'];
		
// 			if ($file != "." && $file != ".." && ($file_ext == 'gif' || $file_ext == 'jpg' || $file_ext == 'png') ) {
// 				array_push($icons_array,$icon_path.$file);
// 			}
// 		}
// 	}
/** 	?>
          	   
// 		<div id="dhp_icon_cont">
        	
// 		<?php $i = 1; foreach ($icons_array as $icon){ ?>
// 		  <div class="dhp_icon" id="icon_<?php echo $i;?>">
// 		  <img src="<?php echo $icon; $i++; ?>" /> 
// 		  </div>
// 		<?php } ?>
        
// 		 </div> 
//          <div id="icon-cats"><ul>
         
//          </ul></div>
         
         	
// 	<?php
// } // dhp_deploy_icons()
**/
